"""Prepare real held-out-seed inputs and a launch manifest; never fabricate rewards."""

import argparse
import hashlib
import json
from pathlib import Path
import shlex

from .build_inputs import MATH_DATASET, MATH_REVISION, build, dedupe, has_gold, load_rows, record_id
from .plan import DEFAULT_PLAN, digest, input_path, load_plan, validate_inputs
from .runtime import atomic_json
from .run_experiment import math_reward


def prepare(plan_path: Path, rows_path: Path | None = None) -> dict:
    plan = load_plan(plan_path)
    rows = load_rows("math_train", rows_path)
    source_hash = hashlib.sha256(json.dumps(rows, sort_keys=True, ensure_ascii=False).encode()).hexdigest()
    excluded = [{"id": record_id("math_train", r["question"]), "reason": "empty source gold answer"}
                for r in rows if not has_gold(r)]
    repo = Path(__file__).resolve().parents[1]
    def portable(path):
        try:
            return str(path.resolve().relative_to(repo))
        except ValueError:
            return str(path)
    entries = []
    checked = set()
    for seed in plan["seeds"]:
        bundle = build("math_train", rows, split_seed=0, kind="math", ranking_validation=50,
                       cache=None, provenance={
                           "source": f"https://huggingface.co/datasets/{MATH_DATASET}",
                           "dataset_revision": MATH_REVISION, "source_split": "train",
                           "source_rows_sha256": source_hash, "experiment_seed": seed,
                           "excluded_before_split": excluded,
                           "verifier": plan["verifier"],
                           "split_policy": "same data split (seed 0) for every training seed; no reward-based filtering",
                           "online_validation_policy": "50 explicitly fixed validation prompts for new rebuttal runs",
                           **({"local_rows": str(rows_path), "local_rows_sha256": digest(rows_path)} if rows_path else {}),
                       })
        for rid, record in bundle["records"].items():
            if rid not in checked:
                if math_reward(record, record["answer"]) != 1.0:
                    raise ValueError(f"gold answer does not self-verify: {rid}")
                checked.add(rid)
        path = input_path(plan_path, plan, seed)
        if path.exists():
            existing = json.loads(path.read_text())
            for key in ("records", "candidate_ids", "validation_pool_ids", "ranking_validation_ids", "evaluation_ids"):
                if existing[key] != bundle[key]:
                    raise ValueError(f"refusing to replace different experimental inputs: {path}")
            validate_inputs(existing, require_cache=False)
            bundle = existing
        else:
            atomic_json(path, bundle)
        cached = len(bundle["cached_rewards"])
        command = ["torchrun", "--standalone", "--nproc_per_node=4", "-m", "srgc_rebuttal.build_cache",
                   "--plan", portable(plan_path), "--bundle", portable(path), "--cache-seed", str(seed)]
        entries.append({"seed": seed, "input": portable(path), "input_sha256": digest(path),
                        "candidate_count": 400, "validation_pool_count": 100, "ranking_validation_count": 50,
                        "evaluation_count": 300, "cached_candidate_count": cached,
                        "ready_for_training": cached == 400, "cache_command": shlex.join(command)})
    return {"schema": "srgc-rebuttal-preparation-v1", "plan_sha256": digest(plan_path),
            "source": MATH_DATASET, "source_revision": MATH_REVISION, "source_split": "train",
            "source_rows": len(rows), "distinct_source_rows": len(dedupe(rows)),
            "excluded_before_split": excluded,
            "source_rows_sha256": source_hash, "distinct_gold_answers_checked": len(checked),
            "selection_interval": 25, "top_four_reused_until_next_refresh": True,
            "status": "ready for GPU training" if all(e["ready_for_training"] for e in entries)
                      else "real inputs prepared; GPU cache generation pending",
            "jobs": entries, "training_job_count": 25, "experiment_results": "not generated by this preparation"}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--plan", type=Path, default=DEFAULT_PLAN)
    parser.add_argument("--rows", type=Path, help="optional local copy of the same MATH train rows")
    parser.add_argument("--report", type=Path)
    args = parser.parse_args()
    report = prepare(args.plan, args.rows)
    destination = args.report or args.plan.parent / "prepared_inputs.json"
    atomic_json(destination, report)
    print(f"{report['status']}; {len(report['jobs'])} seeds; report: {destination}")


if __name__ == "__main__":
    main()
