#!/usr/bin/env python3
"""Generate the self-contained Pair owner-node handoff launcher, without imports.

The generated shell script embeds the maintained Python helpers. Its runtime
does not fetch code, update a checkout, or write temporary helper files.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import json
from pathlib import Path
import textwrap
import zlib


MODULES = ("selector_pair_diagnostic", "selector_pair_handoff")

TEMPLATE = r'''#!/usr/bin/env bash
# Self-contained owner-node handoff. No git pull, network, or extracted helpers.
# Generated by scripts/build_selector_pair_handoff.py; edit the Python sources.
set -euo pipefail
export PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
export OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1
exec python3 -B - "$0" "$@" <<'PAIR_HANDOFF_PYTHON'
import base64
import hashlib
import json
import os
from pathlib import Path
import sys
import types
import zlib

PAYLOAD = """
@PAYLOAD@
"""
EXPECTED_SHA256 = "@SHA256@"

def run():
    wrapper = Path(sys.argv[1]).resolve()
    work = Path(os.environ.get(
        'OM_WORK', '/group-volume/' + os.environ.get('OM_USER', 'minsoo3.kim')
        + '/offpolicy-misranking'))
    candidates = []
    if wrapper.parent.name == 'scripts':
        candidates.append(wrapper.parent.parent)
    candidates.extend((Path.cwd(), work))
    repo = next((path.resolve() for path in candidates
                 if (path / 'src/selector_pair_gpu.py').is_file()), None)
    if repo is None:
        print('[handoff-abort] existing Pair checkout not found; run this file '
              'from the existing repository; nothing was stopped or changed',
              file=sys.stderr, flush=True)
        return 2
    raw = zlib.decompress(base64.b85decode(''.join(PAYLOAD.split())))
    if hashlib.sha256(raw).hexdigest() != EXPECTED_SHA256:
        raise RuntimeError('embedded handoff payload checksum mismatch')
    sources = json.loads(raw)
    for name in ('selector_pair_diagnostic', 'selector_pair_handoff'):
        module = types.ModuleType(name)
        module.__file__ = str(repo / 'scripts' / (name + '.py'))
        sys.modules[name] = module
        exec(compile(sources[name], module.__file__, 'exec'), module.__dict__)
    sys.argv = [str(repo / 'scripts/selector_pair_handoff.py'), *sys.argv[2:]]
    return sys.modules['selector_pair_handoff'].main()

raise SystemExit(run())
PAIR_HANDOFF_PYTHON
'''


def render(repo: Path) -> str:
    sources = {name: (repo / 'scripts' / (name + '.py')).read_text(encoding='utf-8')
               for name in MODULES}
    raw = json.dumps(sources, sort_keys=True, separators=(',', ':')).encode('utf-8')
    encoded = base64.b85encode(zlib.compress(raw, level=9)).decode('ascii')
    return TEMPLATE.replace('@PAYLOAD@', '\n'.join(textwrap.wrap(encoded, width=100,
                            break_on_hyphens=False))).replace(
                                '@SHA256@', hashlib.sha256(raw).hexdigest())


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true',
                        help='fail if the committed launcher differs from its maintained sources')
    args = parser.parse_args(argv)
    repo = Path(__file__).resolve().parents[1]
    target = repo / 'scripts/restart_selector_pair.sh'
    generated = render(repo)
    if args.check:
        if not target.is_file() or target.read_text(encoding='utf-8') != generated:
            print('restart_selector_pair.sh is not synchronized; run '
                  'python3 scripts/build_selector_pair_handoff.py')
            return 1
        print('restart_selector_pair.sh matches the maintained handoff sources')
        return 0
    target.write_text(generated, encoding='utf-8')
    print(target)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
