#!/usr/bin/env bash
# Self-contained handoff. No git pull or live-source edits; exact runtime pin.
# Generated by scripts/build_selector_pair_handoff.py; edit the Python sources.
set -euo pipefail
export PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
export OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1
exec python3 -B - "$0" "$@" <<'PAIR_HANDOFF_PYTHON'
import base64
import hashlib
import json
import os
from pathlib import Path
import sys
import types
import zlib

PAYLOAD = """
c-rlKX?NSkvfy7qoO2$CgoG9^ap*8}yfBF-wxqG-+}x2lI3Nj1h)94B0JTJq|9xufMmH9cay)0|!`zt{i$J57>gw97`r%0)&7(<?
X2CLyvtSx6=jr{E{*%x2|IUi=GIENm$jPFcIJ%9d&M7o={&N+r;MpoE;zi`##>G{-DxB4F8WwSK>4eTazKNX4RW!MV7e06PIhkeY
!U=-es#s-F5IFH-nP!C(CP`YrmuZrJPCh5{bdn}TbXUydarvmYUq-q98D&|L>R+=-Qq1+Qt1!PZKaI<Vf8}X8N}9{GmSKS(s5za&
&#rR{^E^%S_zr*SZxqPNndDciA}$Bd<I5y8e!}9)AFJ^)OD9oYeqDswES^W@?`W~K9{`jQGM|&vqvPY@yWs7~hYv^R&cJbhe13TF
bo_L7`1Ih1AAfi`J)DK(arErz?AhV;#mkrD@$=`;pT3wz?&svg>pz3nAK(6V^v5uG^Y8QF8GL_m_|o~#IoLmZCjW4=Uyk0>>%)Ec
A3i!h`ek@V1Nw+3J=uC6Vd?VJrqRr~jEhbdEz_>^U6@_wUBH7yTnuU>cWFt08iODAz5eIKf&Vd*yh&Hd6d*Q*mwWIJ>@ncS)QRTd
G6(d-@48N$Oy;X8qZ&YWK8H86sF+-7RKp%8>0*K34x9@YX6AMsxAzwQn->|)(!&Q6d<;9_uNGl`J=otrJalFHBkm?jZlH^4JSjS9
?!&J*OOvki>(O~|KK%IM==k;f;Pm6khtu<cyYKRg<CEay@bvxbx5MD%&3_-hJwF?`2d>8*;(0Ofz&}lwQPPpwc4hGcv%%5nke&lH
YR|dP=KsND2k?LRZI~5765R$ld<Z9PaGtFq&k1u!I_sDH!05|W(Z%xxNDgZs-xpDsW#N4XKxX_XKbc11bRH)WG$y=Qq;RCuB%X9U
=X<r;W%DAt@7wccn5cv0zl&z!YF?blgAUI$ozMIA<>F&Mi!S55h_a4?4MVYO^f~-vczh1q^7>uZ>8Ldlf_mN~dIhMo_R0|JIxq0h
HT8OX1?QUkzKn`s5iUDkzj+6<Xc5K<;`pEhZ?6X4=8xl<@%>K&XTRT$CRrHgk@JyH^bl9jnYl#f6@iDt<2>MrxY!@9X$Dh7l2=ZW
+LRvt2$Rcb>b6X4mS)a%bl-J=_9qMmhGb_ECmlWGuHzqi-i9epu2#u4zy;1@2B7IcpFUE|bo>|no1}=TybJBU0FVHT+*yCqF%oQ8
B^n=$0lm#%A{&d7Rn*>Uyqe7-z^O^Nge76mz(&K3(}opx_%l3S_=^_dIX`1BTh{W}{f_P?Q8a}ukBeMr10NgL+qNhl7<iOSWp;M!
FT(FhIz<|zj^k|z3`en&MR?co_xBIFW!L5r#APfC=S`SLL;4e_U=tB4<qkhzEteUL(>dkw-lysHYDpk#!cM@(>v%q2UTSi&jFFy`
G~k~d{rdaS`}dUvSu3eR2sf&H1pAK5uMGUH^DZScjwV+rt~@Ow=hMgcK!qk5Y#Z!oIENp?w-)fA>%cJ#vvFKxVRkQk#cvq<5lAu%
V`Rde=nfy_JlEbUfH@o&+~V6byN-aDtda%_kwqX6Cd62BA<SMWQ{>?+3X*UUb?`q5?imOK1(KeDEu?WHZUX@8AY||nE?Ir!$9WKr
^K`x{BH%3W#`S#{DUxon1a_I*5P@baIB*ls`DUPdc0a@as0VY7EpT*K39gAGP9lSGk|@DifUBS*kWpinK;dr!Btf~7xVj|pfVg#>
CVCG12%%(2j)Y6}Ce9sf4+0j<lb>nm%|$E$4vDLMwoizY+;=8~aWHpx|KRZHv*#~<c==;Ep1{mpqVW@aCtq#>Mx5M)^LT1OfxlEh
u!V)|m?XMV(sU<b(L+Fxe1}pVf3Ad2lxjU-+*!O-2TVwTIT2%oWfms|VEctB>5f>wL|oRYkU;Q(|6LP1)SQr%A)M1}zRIsy+$zT~
rceFS+<Qsd1BENsKW?+Qh<enZcLgL8U!+-l87Ji`Z6qz1Eb_efbs+~xLEQj0j9u9#L<*x*08bB&PtLveZlWxn-Rr)AUAg~DLCo!L
=2VU~k!gfvrK4wrli-fFpqQ<@D!eDsSlm0)G|CB`7a?whI(cbY<TkYCd9TPKSr(r2UYgAB>F3{V`_a57<x(<U3(${!7Z$dh!*KjV
!yBje;N}@AD)|JO7rDCz8U~6$9>MHzrrx7Kph!5J{RQ-cNS&vvY(lhb9wL#BGBpJxQwWI*B6fJX=?|oq1S6cHJg7|*{=5PHpJwj5
0vGAVC&eU3#*35u&s7W@3^pcrJyQFq4fG%_{NfJC!bs7DC~DuKjQ%^XZV&Dq>UXrN`eyN7J+pOUO*NJvsYbxjixhND82Vw|b@urs
!X-;@5ehg3*~&5RW#3}rxS`OrUzKdCaw491lnb-)miQkG2%i}}<B2^m4)_9as!Qh+I6O)o_+=jdjbCzS^0D!a>R855nCY&HS?{IE
q$_OLT2V<7#`APc1Oexwn8d@_J=ouW@$4DQm;U_W`Ez&O-zspp4V;nS1j1d8n*aR*gvM*ar8Mb*aK4&{nFBI8?2|Qjh5?dw1rmD!
)ZnL@mb5FsLK;ean1eEsd_SNUrWndtM8|0av+Cfqc<Wwz&VM-j=?_2r(50_v8}*ii`6P~A&z?E5Xw@Z(|E2W?pu$t&hnD^23t`Wi
Ku(GPfy`0^Oj@;Pn-wpYD}Q-!P=-C|GO*hC`ISl4^qL+;*y>cwpmA!RVFrBsrb0U8Arp5v%)kr=K$=<zhxA0^7tsO3up`zypNu-9
BM#!!e}m%f(Md-}0{s*>ec)z&m#iD(RWhBM(mj%tMYI^>B9i)R<MeVXpAN9%D0|Q=?1;RI^J$D$6q53c=5}|jXI!?|?yNxrYF2gy
G4$666qdVb{z4_xjynd2Apkdwvq7qcuUARg7tsRjitt12a%E|J`t*qdh}x&L4G?q&zTp$@=-u*(_Q^rU*NeK=*0u<9md-Rr9XfZ|
KF#OxR}fu@$5oa9yB>uLwAB%wpyHi{lY&6a)2eT$d?Ombjx$sOgFVx*2&*%~XD}Zggv~Srr|&JEWsouaz*FGdaW)0e5s+fl`QJ1j
WKE9ZQH~4qKy{9I0Z14YiG_E}x#5qxEe575-UXmp;Xw!c^ZcvmZW>=kdBK7ypwX9XIT;_4!rpo$x5oApkF6|@4ob;VaMDa)O4>|K
{OjmG=NT##mq%OZtToGYVN6Le2kO6~xYDyyYh8p%JOdB~Gc+gQyEe5|z6V|cM0^ptec&9zEqbJu#h||9zAOE#cXNQWTU3(%W7OS>
6zK9o`pyG_vyXGQ3J;&ZfG5Vb!vjWGbK_wG2y<x36vZW(pkHG5x=r6vVs+QrJEU8An!z#|T0W?Q3)m}fy)J>u3RVZ$&Siu~`wHWP
rSmJadWgg%#5XOBS5=bUiUe8^3t?*zp4d<5DCrCOp>4W<1&?N{oHgd<Je-hVuMi}Uq6Dc!q@~etK2L#><3xz3;^_oE629>)twWP$
*{D&wshK|~>R-1J`TRB)N~p*B2Ay0=U%_7Via?i7=O9G`)?yDicATQ=Zho!74=rFB2;_Y5O9)8jRXDn4ZQNCbNRUlvK;FlW9@lgB
oI10HX=Cf!w$ejoF$#)Qrsnx!9xM?A&`ema3G$t}tjVWk;HsQx-~eL@T2Z6y#y0zz&>(nzIV=oo;10{Lz%iMn>bp6*YCB$|_=2ze
v*76L<M7uGegwK}K*w}P(3v`l1un$njgZnF9kt4Vqg=8LV?#?dJz}^&I~5;qo5N{?wqwm#k@2l_mf4__*q^82H1Ejngwp_R>_Ev(
PV|U*HO@zQpLUuT5+FaEPD_LCuHr0UVwzb(qM}6T(`)MwjnVR@;z49lW~BOX@@{A&6#|CaUocZ?p>t_w@3!$7ai5X*7&*k$vWYnE
3Q}f)XlSr`q}SkKAtWI6$j!#A{J<!6?M4v^_Vxjlh|%>n4;SNU*q2XOur!S|Xk&2OoQFJ3pN+GPZYkI&X;hKuG*np{7<~y?$xwh0
+8M5GXo^e=S?D*+Lu;t$IsfH6C?c_b3}0uZR>b_q`6<am6J<KqhQLwdOIwwA5fobZ3C}?fXIdux#WhMU<Y)@gYtzmybX!g43k4kZ
(kLm%nuB)6tj6;=zv^JzPKqwIuE<q(Xv=#bC3j9(fb={8Y$Dc2=i&H7VnzB+5`j3U<Ru4w0FwrhXR$2qc|KNv3!JkF961h)^54FD
|GtBSrR%KnD4^&l6CN_;z=4^C1xP&jIT`Hnd01fF3(4RbeDXzIL2QDZEG$WThPcPDnNV;S=;h%}7|+8ovb!YJfR^@C*P5sgAf$z%
?OB#M31W0#>R)h*vS4XE*z$S>??=`kfY<o4gd+7(fk3Bsu)p6$S#Oq$s;KuG=uN|0-hMRC8c-AGwG4#uAGAjuujb=L4o~m=;qcF+
8kgUSy5VvefjB#LrmKw3RS{m&Y1ZfX6}Ht8QsHG7CzeZ=MmRa+&L^zROw!eS$_Ih=8pOwYh5R-5rFP$92w@;EIP6O6c*|7Dck~=L
Bc0zw9W-H03KMsgrLE@otk~w!7*<m<rA<k$XyiQ*^U*D>md(d~;8-vBOdnwGRy(3^l$(<F9QT(x+Ot(qIk4&EIuN;5HFJFek&o}(
()FrZeoZ<mXh5A?!D!`Z%$CFNg)ifa{;pwOPxs4~9O#5QSi#+T=ojrT25<T^9Ik`^>B^J$CvSfbhJOMxGkzbxX^_>%AP8LBk5$A6
b_mNpI;nbkjZ;@!&d+63$|K~`5IR7sb0gRRwi#1Gps0Bf&*x4!DH`mN1SgzOK98bh$3L(sgedLA^Kw@D8dUtstlP{4)o_$X-#2|6
13Kw|4m$$)!NT=*o7da0?C?AcZ;7I(iXx~WSY+_{cLzw<EWR7aaY0)=oWlX1KyOoMVY_X`GO9F17V=3g=hmcqYDt6*2qKV(ae*Mv
b(+MJO=9ugHnEuegDe13kN}&PS|&ERf)#fRYoPjH$6T2b7Cr8f6*N-armMv=@09LOG)V<$HIyLI?=k)*sUopLxKb!;!?{-R$*>i~
338i$O;*<*>EqA<t#6%^1XxwNLf=3Ps0;tdsL@m(Ps7f`Vpyo~+iy@GDdOAD7HEt&qydpkn~xD;?z9Xb*?5RvRYEJv(5Z&gRXJ5p
y4AS;IJ`_!IJy%Z+y4=$8$~cUmSvSlK1iMzA2C5WjX;qX=@Q@}(P~I>qG?<(gnVT6X9Zwm2+A!8m4r~(v+uli@&#-hG1ZK$uX%XG
(W5zxK&b_Y7FkTvVxGd2IRBhXK<bT?9P!0T=Tp*0vvfX3o486h;NW;7tQqJlml-D?K$qx}&C<W4goG)a-<KpH04ynvWycHyE3IH*
<_m1fF(~r_0PNA`G=a9X0CexFfc|IuKfd^!{Ett=PeY7AKlymBU%e<}{NJ9OomXEQI<(Vs%07EeLvKCjuoUse7_%QuJ4i9Ka2MVZ
<-9ADbH%g5%HX|+fysKDek~plKUP-Q6f}Qw-T<Mw_+^z5lTF7c%ksXFPof~XmQihjGB8NCh4ak$J$~blkVM&0b>Zzr-&`loi-+<?
%InS%-2*p<<C8_?8sa88hNpxB*|iAYNg-BYR2+ufH^i-73?Sk@Gp!udo#8*T{ANG%Xf+A(k8r-yzB^F-s9)@k+w17wisy#iUTS4P
6T*3r-X?JVL_S08B<~Fde+=AzeLOlJYO@QPwP5nt(l<@2I_PTPU@pZX{0pW<HZWk1)9A({HEIzjwa4lgypq0nHmDqqY9To0PQW}-
%Eq~1K+?hfvzO0*c;QtySd>r|g@tmT%}hZ4nNM>o2&W#3!Hod3otG3B+WXmML4&?cGx_V{=?E=12)eCdKy`tJzy@Lrf(dhBSgn+v
pN~`+S-;AWm*m<e&ctn>jjE1t41v=zDLl-<3$IHb$$0uV4eWWStEzpiMO&BHw{@N9R;S@nA;qcwT#LuyE%)(cC({nJv2j*hWoQrM
mY#Rfe>O4<HB3>1c{q+3GrBmE+GQO|JxQ1M&TNJ9d3Je2+>WEC`%V-S>0wn^Vv!t73?OeLu+j-kCKrJLG)Tsn8ak502}VZDoGeJo
aJQkP6&N@pyYDo*>(VIX7)w?QR4}3rja!L2BcU2!c)k&?*Ak^ef=ST!wmEjECUv88iNpJ8J{L4yBwr(TQOGYiD|m8v&g_?U-Fkcm
`2=xjoB_~;Xr3-9bqiE|{C5U&*xwYt1BwDl-}q;g<iO~A@?_c?Z|cSg=ZDSsALbzxuLN{wMS+YYi1l!T%3m-YOf#rPH!AP9`%r=U
nqz(*O5mVlzWkBMQV9y5pRAJW1TgvYleNvcTtv7@dYQz31I`InzjCIGy<wiOaDxj6uslsJbEilhYrl+)J(Gu0D5>IFFB|gmU@*->
iVOs~EDz^hEs!CalLQ7}r!=T}dPziY9!)Rt;F`8e97|h&;BS4D$pkbdI-3^SB%}muIQWcH7xa~AWL;<9b`qnvZAu$Io5z<|g+}V0
WFp`L5L7WnEY}gGXi@JXeb2jM?x%_DcY()rm9JWCK*aAkvc@uh8zyk(MAD7&%x+N8d3QHae$%9_A%k6-4o?NbM#oQO2vXFLM#C}<
H(f=Nsb;dV`vgHVgZ4#-dLZYQE3aJKk!C;Yf}t?OBNug~{jPJxy;1aEecP@3d<mhtyfV*ga^FQ$@~Y74YFw)$hR?3Szq-!({Zjq;
x+t=Eyegu`Tp%@Z#Z`WZ@A%|InM6}BR(T<uX0e3lEEa<111A*is!lj12TV!`6k)_9Adu=0Pg@RL5}pB~MWA3J1z8n)6VUL)REmcI
m8%)-;Wz}1PM=p7Lk*{BEh;$)p9DTQX%Z~cc|0LfPv#ZMJAhNaMDX^k_xh<ctVTP)i6Y*Vq2}6o?lqWZ@*-N&$cN9n&hveg(DoaR
F)0WgLKcv1>eCB9Wd3_huld=`%^z_1b+359G1mCdrC#JcYT-S3*X(&L$;o7u!7ACRg9~3oA+nZ*{Jexw1MAtA%m!h-u)}b6r>hAA
xqOJy2XP|U=XAk8+nt(XxIhCrL8;A7C3$yDwaU*BE?IhsscxLn?LFpG0?l4y2b=B1hax3$POMONl>W%G`IB=9qB{Mqefv|BZPu{g
OyLxx94npr%XC>0)^+1e1bG)>oK7w%E%^jy8fRvt3aE8}3R&D3!a5_V68dA&t*x1kmHHku^wwNoYVk7z3=jU}joB?GbYl#f>?UaK
p7m<>hA?9ZNOjy0IMvVrZ!zjwR33o3GsB4=T!V_y;U$qx&VSd4CnP7()=Z?0hj|*q_9Ii_7{t8jq3f2%5#ntAT@#jTv`+9=aXONc
c#Xud6o#WMpyjMaa}8y7`wpsy95JOt*Rqu@Csn{}Cgbo)-?UGfU{n`S=efdiH=aP`+Zo9nqUy1zb{*XhI4XqlYVbc7`y&+LkmE%S
c2d<5YVC0?EL7fJ^y!_UKTgmBIVnU=M!9=H3v-eBO<a%cAsCR1rY9SVTg2U~l!9j1_=ge{J|LH~r(FCAd%)eZ;rrp+^OKLx>FcA9
4m!e|cSo;(Jw7=*Kf<aOGZ&t{ejoe>51a?=hx{<^$CDHIjbqmH?Od!|&^tMP|8F1Gug$w??OmcR4fFfaZn6hhvzizAo^ggq+Ry<)
e!cIv%5shN?p)kn$1oXHPlld>2oqu?B8r^%N}+O2?*S5t&W?6RO{t)|kAYcD1G?zwdLNZ!#QX~IW^jO!4(@NTbazB)_hb#`#A9~Y
>_QCCJSpxSm4W`W%jSC7`mz_=MRl5I?%UsnZ+}1egxexZka86|wUI&(<Q3zr3Jch8P!8?1)>3*kpmNSr9NsPAz+2+BHMeqV(!J`N
yaJ{0MO9!-m$kh!+Nr!tnAdiXFn?zGgwKB4;uGH4`D?EqPfI|DYm8q;(>?{@+)d`I9NjTj6t;_T6hz>iB)Szhjv|=VdBAQxV$}Q!
4HZ4q3qYG0gJ2XE<P$-6ND(GnbfY$(DJT)>T5FQrwm|aJv5h{zfHZcT7QdjvUxiuQtR-5kuL#B-;mIxR_yo>1ndR9X=q#XHGL!+&
!P-*DU4Y2X;>#5hWc;pz&VtP(P2ElUt%s_d4O&M)F#+K9od*oI>A;7cA5dyj5Ue@0X7B({efo3VoNBHu%njymBIJ0uytczvs*YY$
pQhCst(_Q4PVf4gq)oD1mIW}xl37lM?U_3%v|dZsuHpiKQ(-*M&9E)E75XRtIv#%Hoy-=1zyvbj%vl1R=1I5&(pwO_8!&Iei4Gp%
KWpcKhF(|l2y4)=k&g$&hDavypwN(W$~(X!7<<RRob6Fu`4VI4s5@s7-m^2_Cr$)Q1^$C9h~#5#<g1AQ{Zony1uq$<SIhJuh6dWg
Hgg(D7qBuV9WWJtX>I}@hXD=RQ~evtG;m<lXbe*esk$!N-(6*hr1R8!j-EB_?kDGk5tH++a}N4)q`VP8XeutWWM2BdfhVtk2WRo$
9I}EoL@s1v25sD-^n%;}=4|-!kKsGn;c}LrpWu_vPrAUd{@dp#-kLl)k==wInQfZXad&wY=9LfW5q?<d?b7HCx`W??2l!9l-=D2>
+A}~s`0x5v(@@_#7)mvv@I{fBT{6_t9<YU)jW>erjsm~e)S3H=aII`jyp+-VDqgy6asop4qW{DG{>T?kK!@TiKz4Cl&wQ52GgD^N
2St1uQ&4w`$SE0jA8--XEed^5H4rjr1t4XfC!s!ah>4x6$x0cZ0Y`rLe}P2Up<#72h%Ik(^BVpu&vC8j3p*g#3@_)XRkUWS@{vRf
=xGyD?TKZGR#k=$5Lc4O0n&O^RNNLDb=4f*CY_(ZKKtGI*XyHmXZXj_yW#QMVO>0ak5~ZsHIDcwE>bicQRswmD7$R%jWT5q#B)f&
7>S}*wVqD}X^9xHSRz)>oCx4JGE9xHh`<4`7Ry|D5MWj}QHh}>ewSu%@p?tmCcF0z=4k|EV?b-8t2zSB8iRm2qE5tvaxxUT$cw8@
r_MerQ~!s#3C)7**AQMGCBT}FAuSm8STJ<ITpau=E8Qt{^NUt0f-*0&m%{%?bnU4asjstcH5fV<dtuR|<LcJLt4$)a*^Mehu%pAl
3@!EQ@~`D-6m_lNB=5TBfnnkjNrVbU@%@7%^LW>hkO&ajNSy)xMSXOszGi!>l1UmW$^CB2oE~6peg1U;e~wh~K@`()*;KfMe^R4$
wUUypT@2rze0=9TG`pJCluvF1OUk0y{~S<SIh&!pM<dTN%=52@FqLI}Iz|i7>o@O*txIdxp-L*uJ{*v)y5#Mltk_ORx#-0~!v3G9
9w;as<+7J&UFW&ywfT*x$A927A|U|%lr?8ilSQ6XX>H`7Me)Byv_*rTxo79E&xe?`3?Hrc9_S+xc2OC+9z2+=O2*m);e`UEIQ+j&
_N@xS9L}(%Th+?$-faw>XHOc6@)iGI-AhF~Sh@up8hD&hP3p|Ru@Hf!zE1NBTZd-nSKGMqwyn=*zhzVBRbS>~MzK1#e0E;5>xW_9
1<7wg)m>x@TA1EreV>f>k8*dmITB%l&5gw(s8LS*2Ikae?gRf^_j(V|(b}{aZaGgRLRXH{p6YIodXuF$oCExOhoi*DsR;AyhCWOm
CmbhiwfiBJgG%n=9=o6FBPbAmeqwr;_k4Q3@x+z|4mirB;>*RL^RU2p;ewqsUB_yG#X5m6$-5nvvcXkc>AJ}oyvqm*7M7#E>Qvs~
X|lx{WgNk1Ff<WREEpPWgILZrh&5Ak$&~>sE?O!c;Rtk>+?ha{#z4-?eut2qV`emTr&U?@>Os<4QKtB*GGMwMj9rhMhPFm{@`ea%
MCz6>YI>#80E}qr7aPN=8$-qaX<RirnjU2f7~XNVK?40{t0k6+q21T(QC2PxMB)XKO3X5!r(*cPreDVnfN}PQ3E*+wIEv;$CLU9i
?+n($8J)^9@ayR(Qtv6YOpLY#S_%?s(O?-kqvQ*%TZ_Su9Olyq2`?pKOk#}Yoy8M}ia)UZkH=td9otgHOV}_BW!p&5AFI`?gkpQq
?n8bPG@NDtZYeR35*<yABbb;xu~`J9{Sa+L+6Nfjg$vY2xBvsa!x%lwLV->=(O6W8_x~Gait4d!%nz{48LGdUEn`!K6T_d}tiv(+
v7ypb9KFJVv5p|RD0!qc7ib0+Ce&!{a4CerL#5^ezBH>R)L57`jzO$c)yc;zNtKy@I66B!I{wv|yt`|Z-=`$TxqP7xrN?X5n&2rs
s3=eWKlrX$L>AGw^Ch8jTe$f4@I6})X%#)J`cO1mLvHSxLbR4`Hi|KlacYZHKody-ns1Og+bwjPh`?cEq1(oAqTSBn<8MFM<e_Xn
ep?iWFE(iyhx4B<NjOw{%pNrpPN=V0!65UCQTqo*&WGeVl_?)cMa{&eO6iFW*I!UN6NjDjx68iUSHBxJwpkC;TW|Y^k2WH<r|(;a
MUoL!t(T<5zSzE%3I{pteDhZd?H|c{8oMI=DGvYz+&&PZD4c%9ygLA<Jb1wHxIX5Ij*v-ryp0&o^|@6&KJh$jRm$V63$Dv|qpImO
_@}8GAl&N>*c~UBkNwZbl8!bGR_2kYq%mG+Pfue5OtgGD*m_*c0P-fK+*ZW5A?|L6isfkQP$`;kauv>+X}zbY;lvRiqHIR0n~KB8
4k@J<w#dhVf>~$RGpHb`khh`i@FV!ew!DmHhMVVGZwNAD)9I=err7GI#@wDdF8YnE?<;Ug(R4PmlnN^Z9sT|A-LJ!s?S6}|Ceyc0
!|;kcxDpo4B~keYR!v2RYoJa#z7~joNmRD-vITtS8TY5Fs8)6g2PaK5;5~(={KtCJsUSLZBc(-o72A0&(KIqG)aV*s0>ca50b?s+
P^ZJ=fbJlxx}a!)TCt8@SGC)G<b3c~X~q^3`XyPWSlv;*)O|m=K9URH-x>#BU+>ZJAFtmZy;Gf0zCR^MNoExlwdGW&_G`!<FVJYc
ye65eNPjkW(~tGWB$~}#3fy}XT>ZFCTRPk&v8T$ecBEU4BW|JLtiD!t98qdFQetlNIEzhfw=qcv4Zg&@xyP>aosb6^;c}jiJ8l{3
-un&?>7z(dV~4)kqhBnRU)rm5TUyJ_%oa~ZL(Q5dKH5A471&fzp=+Boh%WjEhc8F{o#k=;<v-h_=7WEF^8V=Uzga<6#y0Hjm6Kn`
XouY8u<w50X;}##Ja&gYthcwf1wOLQL|MSm&06GBk1^4E?&FmOk}ge`J1vWN5&s=!{<3&<N|Jk-EmP!rMK0z7m8VXq5wIgz&4Y0$
09qL*`XMKV258ycO(xZ`t634x!U>nZQ^>R_3-QZ@+X}*|QNIqp)wW&N(|4s@QI8Rh4dyvVp}4zu-jWLNxVh*xb6pi(_ZL8-UjY#0
jt%m+W9;#6!)^<?{{qmN!T2bl)D16>6ai+66g-&prbV!=$V7U6kCBT6;pj3vO&hV`4p7HO%P+5|(-^Im;aqXTlFAs&N!)Nw2QO%5
H-V15tw4h%{4;HJ!n_9lYpvA=e8zvRUvUv)Dg=t2Ju!EnxW9)zW7x(d%E<pCZltg8#H`hy`T`%O<y&)3J{+B&58r{L57HA>p8WIN
a9SQXAL2L0t<e;_kgpaCEF9P3%B<JO`sbcZyp~ie$K<*buVQ(zG;0SZAA*0KeEgkUhI^M;x?1*b()nr;?LAbQetrUNKb;Lfa>P4q
e4eIH{p)yv!2^5gY{q!j1GOj%DcoB-SV;59h^TO>GyipVxk3Z@DZS}TBfhT*FN_X?X*vl4>r<?u5QOqg$L$e;gh}HeAMh3GQ@+W0
(6~%=k_PA!m0P(9Bzu(3knh<Se%u_uw7o5(laIIul4biG{HqjGIW~91(s!52bHdVH43-As0)zq{UPbdIY&RiOw86<t`5;N;td?ko
>E%?c1@N-Ghw73_+VT`w3&m%hYK*-~JH?m2;p`)l507ZJwfno#R6yqv5Yh^#FS}7E7ydPU?A39&nxVcG9Ls$*Crt7ESE_L5F;MsE
xvGqao&#OO)81NAqg;DAl4fBy#AAzvKl9a$OM&8bfR7QAuwp2$j#i4v=js}++cAc+P?Cg%6tu>ETZK0nESmIH%eRX)j<8?8<J(6n
5d_;fudXO5IF23n_|n}`-ESdu?66Xel4b+V>EE@}A+t|)0m3>#u8y$u0;V1U(t4HpaQjTuV9yjAC);ZfAc+eCSC;`qBm3DsXd{c^
U5rJ=kOF!QB`Og*K&^Cr%HiD-=vG|J?+M^eSXQCs<TAO<Qx%59%m~aZmTQR!<*78~G3O*oZZ65fU0o%*tL+Eqi6!wDSt3@qgigly
3;;ax5nho@kqxz(7?YshZh(WI4?lkJog>6#m60-;M`5yB3jSbWM|dk~qpyHhD#Nv8e{uW+T|L4zGZX3bV<cwA6$Y%pJ^}53_VfGC
30D~HDj-bbTnwW6o+cIgf}qkRMS-zhh7+s=n#Hglb$Q-btDIThsohdc^Pd*aBupxQQli=;N^9o#d9A7@JoC9?QvzTqI{VC`=p+Xu
Ujs8VG!MBy$dl=|)n9cqNQkI+t>n^fCHJR{7-{Y`0@iY`dbBF7cdb(CU8^d3SCVm!BJGq+5$HTm4xsE?)yTi75P4{nBB$7a#?s^4
5^fr5I{$+No1M~4gv=2qsL@r_7;04o>-7Z1nO`aSrwZDuYLa$PkP4%4txJNr{GaF0g|8O}BfI|Oit0KhSg#o+a`p1!pwCGU<PeOL
wxL$JIhg50u5nhXmyy`F_I`?|eJxRnVvaMCtHP1>utSut#iM%<;B|++c{*`+6>q)jQ-!!0Rqa%{bs&V9Ay(a>agXj}kY!N?J{nLJ
OKgBeS%=ZOycgGmUyUj^(_!>yAGf<J?oIe5bu|xu9HE7UTNw2=4@RDp6pYHo`=jawbhrX|kN=<r=N5Y@X9+)>Z%U|k6WvAThxoJQ
L(cie)xbZ-)pDw=r);2oHy>x#5Ew>X^@{;f{-&jrKXLNqFPxE4T_q(wg9|}YW|BTfX&!TQDr_s)johL9rP?=?OECY(s+p_1B&<B3
=tlJjc7*Cu!gpn1%FVbr)7N4m)-T5K<tkm}l!C<9!dEJ*RD>z6k6E3-sCvgAGl`PUbRCX{H80grF%@;9WS1nh_QyKA=H~ddJGz%t
n8n?8R!PB@+7$Zo94YEjk=qn3q)0ng1V>Y%zQUJIH1rZqkZ_}TgZ=ejUA+ZH#{R|WV6%C6i5yhd$qUWOtmFp?7tnu*SJA@bdk57$
!mFlAr@n?t$EZ&V*z(*FI+9-;j>>XVTT7ExEXcYOt_7@==UStVd3N9+^G85RO4&nCqA7!sZ!_6&C$nxMS2J%Y{<_|AcF(NYeZz5s
JK+q67VCU;t_VyrxQ?vtmNoHFFHj|eNc>UAB(vg+({u&e!%>}r8T1E-4piUPF?+-TE6v{ni|T1?G8*t@GYz&cc>35&X%J6KgQ(nm
`Hi|}M(l5815!fq{j>ero+8_xD4cTl4-TI`d;a2wmp_K%3Bbu^myzWv;_kL>u%RaD9fXZ7?*f1yxKJR2Xb#2At=}`N3+%LB38XKS
txQk$kFTZB@4Ah*(l+;CQ*HgSMyFY%$J;g8gepiv2v!!GK0{ZLs`uq^g&#C*Q22dct98y_pc7EuK1u0Jz=$q$IS)<k;GL9e&{a?N
CS*HQj69B{o`8|^pR)AC<zI56CTLkYh2xhv*=11)hMlZ3!nA>-E3E_NnC&Ixyw-hqe)VQe7Tn6uP&_68iAX`EvA6a@SkF_CTJc@S
_>I-#5y?9=nr@+g;rku#)-n*6wn@vK<rbHd+{EwWSyO3x0vPX<D_0FR)eEmdM}4yUv1<^WjU{k@o8})SH%9RxG3AoclySSn9?7ik
xNkqbdma37bawRS{V;ep{Nw2D@C*^@_>ZG^NA)+AJdKLM7==P9NO)5|V7)@xQLgvn_7wAI3@})CZwpZ(5vUC^`aZ-cpG3(tOp3he
#LqBjx@&|UKCHW-rWm_AYAA?m+5kz<YpH2U1%EMTi-OSWRp#*>$p3hSX7wh-cK_=HW-`s_re*^tX&A&md8;+1<`QhX#EdsP<@xeY
7=)OOjMg?yx!QpKZoY?BcSSqV;<{@O4`_E$H_HTVGf@$YHMn%0Q|{n>nqIG#8)F#Tr%8*uputB<25Cs>uq%vifExR}pifUK%s%2e
v?5KBz22KgV+VbRhAYoik|xmDRzmH~XtJg#{S-CZksJn7XQfjiM8mun#8Uouu8gOypeXM%SB3(bo9=bMCY*h?%+R~?f{<FN4EeUy
zsBep<Q&7JljDGVlrED*ZmY|)!cYgUx2`}j5OcGjs9F9))IWSwU)RIhpkYQhjG2UtT{hAeGvAH`ml*9bG3?S8Ra|a9ZFu(e2n|(7
N&`iKDgkO-|I?K~T?4(G|ENO1K366NH5{);oo#rg>pC@6@Yo2O=A+WYnyqtF-u-2|G1PH1K0~k34S5yR9bn`}B8gnx4s9pNQh2~W
KY;e>F|BxH5^~HZcy*sw=NZtji<d=n{#eriv`?Q-o-u8H*i;`)^B|SBd<)F*x2-9D>%3M8v}vYl--dh-K%@$Dp*IKX>&VSz4yCIz
N&@8tSi?ir9o+{<0b5b#=GvVUP9`MZ({-$J3n_^$<wT*i+G3LNd{dk=3gwj0(}r1;wB&|FgG5+1p(c{F)+4CPwwnaOfeX8F`tS4K
PLAK59G}xAQW$IT_T=4g;2t#ic27Q>2FIU11n0kDme(0Iaz6b2zWxv+qu;!LeO7%_in13j4}JRj{5P@^Ach(S6N=?X*$V{P82nIT
r}-fzK3GT#t?DO|4QFLxpquK6q??2g1;R<O3g>V*VRz!>Mv0}Iv4`-dYSVjYpv%kqQpRzD!7S#9RDL14s!(N|ZZ`l@iydw8fUU^R
DF|Yj(G3^a<0c-TX7MH7=BTYQ`{nSda=GQ<IPa*ICLx4XPgVu`sNj3mKz4M_J>;Cys$RBzY>*>mywU@z4y|~-Z_)9Jz%G-q5dl>3
e!fIGFK7>?97Rc4VF;seW*&tZU9?qV7e`bzOlk=SO&>iQK=f*d@CS;ez{bL_vqGJ0iNYZ?hQ0w|De+vWVL3ZHCEJ7|--8J%%j8OL
7?(vI@G5Q3Q2Fr|4AW>LR%7ENOvvkuWegSeZ`4`M>8dCs0wRELNeK(Oh2h5P*t0caD$zE=TY(1YJU6~4ApRMg{O;9^YDQO0J{S~8
Y_~||``u0R-j_p`$~PyMR4BKgl2BxTQx{CN16g04CTmlAb7^PoJJXcRw5cPvB@k~TGKcKx9{=zsvrFH;(+#s`%Kb4+ZOmDXtHrf1
q@s5-N&G|FJF2vHJjaU&RYg!L{z*1@jOxi%Fo|(DDP2cplGojgA-pR_LtzBeh8cm`-B#g3?81EKpNlu8l`#xm<BrfBV<rp(Kf2!W
@6U-@?*zjjkffu>f#QA0mjmJ*7F(uR0iYpaftCg;RKkgc7;@}YujFFK0+nJVPe~b^60q@J?v^uNl-OL0Byz<nqeLF<W-^0b%zL;o
RY-*;i1Dkeqi*}7lu4Mv^Ww}`zXi#F*G?7Q>019}07Qc(&zD`HtEIBj>ll0WT!Iqw)&_W#RvF+-rG@HWD#e#cC0JGp1oit`j~v(3
!!z59@HEnCZ|;_S3;L$=`s~U;JR?+PLs!ObH1~BI#zpUP1q5N^Iv3;RviG0REJQ6R+At!=G&Bz;MI9t3YC|VdT8wL&ZRiR($nB=(
<DSf=Qbny9V2vFzsiP&|spP1ZkV)x@cfZGBGdiJ4UBarWuFFX-Zzi&h{CGGCc@4h7m{%73uoF2jn~@r9yv?qbU*8-RB)4Bn7@q6Z
>;^Ja%l+PUivfXDKH8y@FYB%5J-e)l{!qW&mBQD5R+{Se_1a65t9F^~HC)AOF1@2SPZH|nQg#Z>q<N?iBcM)1j)ZDxcBnci{aYYX
0@nyI(m%>wq~;tL>Rw3b<w)I{t;wJGSFKgp{8O>v+O6cSy2P_K2;nTEfe`SX5OBNWaRm4ov7Esq``#qdjd!5q9W@P?!7#_g3t-;R
H82ymOAM3)`p7kn_rTmv2P8dg$v;nS2E>h<?u}`>6z1S?e@mB~sGLN%K^~DY$Xpe<jBsJbJuq7YJlRFHag7^>(jJEot9#~4e+b^&
fwqc@jK>=(ld<ossq6;+Ke|XJp#Pqp937umq!lEAU5>llDyfjkBPa|0P_-URcEd9*_K-?r$!=4Pj08!%Tb?#<D&-rb1E2n-{55_p
rg07gRY7HL>s&aN;ya`4f+;x}<8TD@=S0H))o`Q+bFQE&)58<?e}&%P(u>Y_-#s8T=sQa0!cJJ`st8-cgUH%L31XBCIFFY>w9Ml<
^Dz*`GPFDenG{O|^q*XTh#F<V7!?4`%NF4stTLPiNt!J<jqwH;F$SEP{Q>U^Fv&#!2<OYIu#$&}#>9KqTYI!#01KxL8Y>Qr)~bmt
l_AvSOaWC18m-#%DJ>H_HNw29zE!1jj0egKV+@Yzr5@!X0_mR#Q-GcD&@>YkgUip=<zcOYDyU7GOsa@+{q-yDLMH@4QrB?)6cH`I
8`b*cC~>y7xxDlynp{($)VKyja!Z>MVjAVPM)fI=h?SKVNziE|ouz~p@et%Wr7g7UygmKY!{URMJ|$&Jkbsw76eU$x@2cj!RlbjU
^O>v`CoJ2c-aNSqNRVsj(4Zkk?2{F>sv+akBU?JzU}>Y|dC{;jrjg?rH^(wIT;NT>8Px<P>3NqM*HNmG<{SyRgXg@AZ`2rz;WDt#
n=AyJ9*VJ>12sWy`6DJs(PyYXHAa-tr=wchjFLv_V<YOxwBqitq;etbBCZ4_sc0p0EkeF4SDW`owKS~yiX_mL37XsMaYL-0)4V#e
HgT5D&P6I))~7CFsVuOuY9(4zrFo(b=T@9TBPm{_gooQXB9^RO8=P&(&Lp%R<d&)qhkmuB+e_&r8urFkJ4?0DR-3KGFuGT}-O=7+
rBPW#m?FN&utnroLz*0oedmEexNZ_yHwvv3yFt_UY{|7MSar<=XT&LQv_nc9O1pMY_WuFFcB^o^gMiCObqr!$HjWF_jZH7*9#Yjk
WHb@oa*a?xZv<QK$Pejo#+<+Pl+4^JZ>|f=<%Yg8+;J^T+eVyS1m`lKg-#n?QC_<n36oN9Fq@Mv1{YQ>_C(X8kGG>5HOl0!(RPC+
djp1lo(?}AeHb2}p9RM!?}owAJCr6GZYVYE2tijnMRvUn&GPEpa15bwyO~+8yF!)B`{vP;Ol9B9I4Y7kj7C)0n_AIjWHp?vG;h6F
jpo$+d9Cu%Kvh1{AC{rwy8Ka%cAMARi|IwdRdKhib%(k<oZ23`7X~G$#@G>bYEn@umH(->Q&(%kIjyxWN;jwUxYKQMhwP@IxH`T~
YAWt+g}OV00^#TtnKj@%Np%1;b?16l%C@JY?o?=yjZ(TSJeR4aBCyL<F8>CYJg!T^+cWAkA*pBYcMCG<%7pf=(-r4f7Q^frG=~6p
gzAG~&}mWs2+i;kXt^}+{3`pQ_{hOPzpmYc!{G6n`>sq1JELM{9n!64pyn1Fd$eGmB(ATJFKDC|=cJw^Pv>X6)z%6cHR|(AU?wPe
xG%;F#59*G0x0Yd3zMb0C}wr|Y`^u!W==Gr?02F}U1gaH*!En%$=TG5nhV3*`BmHi#feP~=mt-z@lj4m^=~|C?uF!e<2!MPl=oVf
X$2xwDiTAcYAN_rIy$!;Z=KexKgJOy56bYh6c`>57cm^&zaw(bV0bNg)K)uRFU%W3{^q7kRf#Ova9^v$yTw?%07F4I#z(p(GpDuX
46v4dO3R$_eMh{XW+%#1OdWW&Y<|NgN(<-wrrf?ym}sP7oKs}7Ri5Ol#t^nv#+yu{s^o16jplS5O6g2unAiMXU$=^P5nd6FO*h88
vn5`ka$}MW&rR-Z*D^PcJ!ndPGe4l?XbfWId2CL_Fvc;(p&h)s{LL2MZmnZG6aqL9+3-@-0zqz>O#^gSxH`f>HQ;o1-3aS41pI7k
>_65QbLcZkil5_=G;Z|Wv~%Q0DO2}-v}T<ZAZB;So08+7roBUMc;M*J@;Q=bdS^!>>VUne#KC9?bnMj9{c24O9M?w$5=DND=Af%P
;6P04VV^pM)s7am;t=UjH0Qc*Q>+!_)Ypy_RM=(-G2m4TDV<H5@A#XVKxNz_*fDHP?5u?Dx8)_2jY+B#yPFRu9dP)&j>N@sXn1oh
zBYS#4I`_-zt+IxO7=o~@BIeA)k4<mfx;p%S0ja$rofy3g|WL{+gNt7H7r}nZ;(e&<}v+L=0FdHpF?`7UX;;2tSpSf{EEUQ<X`x2
wQMTtMCx-RY|I#^k}o<KSY+8q{>1nT%hKw@cnybv_dsf1nCyood#ow7RZXpZ7HBDUz!i)88*Y{qeaKLYDy2@n?S(HnrZV7y06fpN
Y0ElMSK#g$ws90~%5pR5+z9d$w&pu;O`n_D<6@Ol@xTJDWaCI1z0Kf33htpazuR~|mv~U%ydqr~mW-AlC_@UYpY>hr{swY%^>OrU
D<6I3gfoo!T&5Tg9@8xId3uY6z3V-)`s1$UzVlj9Mo|F~4rYJjs4S@no#IW~s#1+nVarkBI}WFovlf^0%|w1vR^oQrr_u!<L9O7t
;m!4ZgK02<q-^0EqG8gjgif!K#ccgX(LMFi4whZH-Z@AAxd3>&$`D8bPN3yY%;*(L-z>l(fnoeJIn?g*lcGT7!de72&C%;Jo6Ul&
y&GYW&5~BTxW?ImhP2k$>n;j|A@6f-GKyAr%K`GnuA3DW{D|K)ezcu-vXg^f@8SVqVLFu~v#XdQChyNrN=;=;5iZ!_!GpQmYfjA9
4>=`&&E>@qPqC&I)-G&RXIN<UYl3e_$v<7y<m~8I?8!6b&X5Yabg48>uz)qvoup(F@E0kF*l7|^IvC|IW`eF`WW#eBCQhh!{}bKA
b%FVq`UKBNbP<`ZnlZr~)#raY7qcnd^uqtQkJ(_Os>qke(-p<Yx6-4=dzEQw>h=NM3qIIb;>rBq7%29&{WwW)8^G2ufm;-36x??d
p;a0SRggySezw4L1`hv`eIY!B2NQU6jXW{U%A{N_1V9B%G34HDotTLRO?O-=|Bl9W3{6B7#Z6}WrR>9AS(_wLg{?5G^;PK+<~tQo
qQ*V(oc|)}T5XBvwR(g!&~2o}HGJ<puVn4wmgMs&T6Pw3((w;5+UpKWm8nf|dibSRm9<&$DQ&z$N%~*udhZ?Vv{jMs0=paSs&|>z
WXVCHG371})w^Ma5_Bm8)?X(qSum}I^ARClfjE<Z{Di^aD2l0lc2$iS7!}jSZ^A6bQ=|$ed<!Z9;~xudno1gZ<x1*HK^;a`M@+gv
JBlsXeZ};7$x~=dp|4pd^y|tVRC4RJ5y$xSqAalVtu6bKUrY(P9PE0<=4_QP)HUkzVzvS00jR#tucG=c!Dgu7X_lu;5^LEP(eR1E
KACi9EQBl1au%0cF3A)TYBoBQ^bJm@V5o@#7J8(sQ`r+twQR8w@Y?KB?zS}PRAUGusrnYHY^feB5U@<d?PUqEV9=wg4u5{Kx$Lkj
Rfnl2NLh2(Z7DhY`N{v2HHWv>8{S%OxOrf6b2j%O3{G`JK9#bc!)N<D77MnmA9D2fou4F-jYq-K+duB_Zw*{l&FOG~W;TwB+X(35
KH)R;;3z*#Jy4~r9=wZV;R~G$K<-g}LE2LK7A($hJ5a3Bm>pdK*l54tgc{{S(u<HtK-Pp!SlVtQOXIG1kBswOyS&O=wSAS95f5_C
BM$GDG4$tcC=M*s?}g(uD^y+JE=foO3`fli(3-Or!Gn9L7n|Pod%Nhc3a^<I#tG~?`t%KQ316i_N`eK$4W9?UoP2yc9Ju>->@k%;
CfJUE$SxwYCYWd$xR0P*wAa4{xvbnPXleOkT?}spff-o*9{M$$a4PxvusS5am?DpSzma<5I`5(htis(J$H|^p?k<!G4_9pB<u<dM
$F-?PDst%`7F=HcZw8)08v
"""
EXPECTED_SHA256 = "716ef12ac96f613ef0fcb95466f1feff8410d17dc441066a6027d9eb5e11e308"

def run():
    wrapper = Path(sys.argv[1]).resolve()
    work = Path(os.environ.get(
        'OM_WORK', '/group-volume/' + os.environ.get('OM_USER', 'minsoo3.kim')
        + '/offpolicy-misranking'))
    candidates = []
    if wrapper.parent.name == 'scripts':
        candidates.append(wrapper.parent.parent)
    candidates.extend((Path.cwd(), work))
    repo = next((path.resolve() for path in candidates
                 if (path / 'src/selector_pair_gpu.py').is_file()), None)
    if repo is None:
        print('[handoff-abort] existing Pair checkout not found; run this file '
              'from the existing repository; nothing was stopped or changed',
              file=sys.stderr, flush=True)
        return 2
    raw = zlib.decompress(base64.b85decode(''.join(PAYLOAD.split())))
    if hashlib.sha256(raw).hexdigest() != EXPECTED_SHA256:
        raise RuntimeError('embedded handoff payload checksum mismatch')
    sources = json.loads(raw)
    for name in ('selector_pair_diagnostic', 'selector_pair_deploy', 'selector_pair_handoff'):
        module = types.ModuleType(name)
        module.__file__ = str(repo / 'scripts' / (name + '.py'))
        sys.modules[name] = module
        exec(compile(sources[name], module.__file__, 'exec'), module.__dict__)
    sys.argv = [str(repo / 'scripts/selector_pair_handoff.py'), *sys.argv[2:]]
    return sys.modules['selector_pair_handoff'].main()

raise SystemExit(run())
PAIR_HANDOFF_PYTHON
