#!/usr/bin/env bash
# Self-contained handoff. No git pull or live-source edits; exact runtime pin.
# Generated by scripts/build_selector_pair_handoff.py; edit the Python sources.
set -euo pipefail
export PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
export OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1
exec python3 -B - "$0" "$@" <<'PAIR_HANDOFF_PYTHON'
import base64
import hashlib
import json
import os
from pathlib import Path
import sys
import types
import zlib

PAYLOAD = """
c-rlKX>;4gw%}huoT>*RAt6e!v(RCtyfBF-wxqJ;+}x2lD3AmtL?plqfLfx*|2}8yMmH9caxzu(VeYFJi$J57)2GjVPCq`&qeV0=
(kxhoaTd&?)gpa(HhA`l{_ng9uOg?oj+`vIjibA0=A1z@=RfOc4bRp|5icX>E-tRqb>Xa6v#^MhD<^ao@onTxucPS=yzsfRPsuz>
mrfAO*Tp)Eg20KFt28T|FiFw^zD$$+Q}QX1r_(ekqWfYIPs&Hd!z#-4&nU~1RR5Y!lVYKNU5EL#`Dt7>{4-C>QPNzdwF(RTK+Wk4
es-NRnCDrV$M^VCf1^NF&LqEH7jZdw9$zJ)@e>wT{#Z{|SvrmK^6MhZ=J6sbe@Dxe{Q#hhkolCH9iN<x-Ue?@-@iY;aE6W>eiO~V
ebJvxqi_1p`{DfP`Q-U*^8Je+zWIJO`)2k{IE{{;A5M?lPs#gNe*~{Sy!rL`_fhcr-xs5E`2O(dd*>_Xuz&Pi{^4dnAHSp5M}7Do
J~}!6d2~(#`iLhz*?J#g>GITO(cHO;i%u4;(ysGWm|f*vz=LI63~M8IX-R+@!yo$I;8Wtj{}@SLr|V<}5Sziv1NaB_81Q4}M2m2h
1Nz~2T_;Yai}j3A4WPSNz?*qgOs_SnVUN>vxx{aW&ZP@8bGwe)djtQ?i;QOJ;e#nYh8^(N%P_wg_WMUiu1tT--9*VPbTNykMJLUD
_!Vbq(sh10z6dTxAKo9Iym}X$eK>u8b}@AOF26WA4L*#{-o1J=3Qk}D&(WKU^Pzj_dfXwN7XuIcvvd_D9hq%c7C$r_9G{KoIY6WK
ocnD4A53-#|Bv5>SrH`BU68|vaMFes**fx^Fn6T0LD>(CzFHSuJYRt1u=dGA5rtV6K6C(N#*gxoSrpC|aS}me!i!}JM><X7X~%QE
R-0WmFS3V$J#U7II#~YOXdbQ?#koA_@J!RiVo+Z$KK8TdD$a{2>nPYT6uU;Bqu)m-7qBg_-gcdiS|cH-=RKiUfJ$qx46&~B?TZ)R
eB0FP-8GzR?)xe#f@Qesc!TC0%%Wu&Cy3+261=?{c$+_t=f?Lx4xRp>9Zj+@&LigopXd>;pfh)g%qs#9hsSxu6LHxeZ)gTHM3R?I
lG>CW{s@z+Xy&#|Yo2D#P4v)pfc7U028Lv387Cb*<F4Z$dES;OPp{X>4ZsD?V+Nq<K%YKR%yjZ6{hOqSsk{sAy#SB^jNI8^+c6Ss
SSK1Ei~+svUm_celXcYIYO<csBfzO?xPm2N&%j2*t<#1TcK9<qUiga^;W<BHFFV%q)cua`r%^P6Esu*_XagS`*W0xy9~gL)%w%?U
>(9dPX*xq1qmJWU2n<KDl4W?`@%#P5ZrQbY1aTRw!g(F$(TM&8D%eDXO1Z<&*Q-?q<8;n=ymx7OvtAL%ny?eF@g`m@R#%!_tYW0+
Bn|lI$G`k`{O(<4LDovD5W<ZrAHlxk@+$*>>AXz|jic#xiYrfx$ocr;9Z;cZ2HOTZ8ZO|6@U100=sIu=!)y{4S(rTtU-28pegcxr
!x))xC%VVSIM0pu5?~I;1-JMv&2A##CF`VtLSzxhg9$N~TnMvQ$`pAxkAfszMjiZ*f_nx6L4l-aXbWlFh}!_bItUqjgiBW6_;DVD
lRRCliwHOiym5WsMT(?btbkqSHbkHq3l7}GbG{hrp50IIKkC7pV+$PJb%JXmiId1+oFq!H7T_xA2xQclB~bXA07+1;B(5$AJRokJ
q=}vbKSC&3k|W^~y@_)N+k=1w^W<k5dJ7RtfJ5SHpZ5uIl84TeFb?MK_79J~dH&+t@4o*boJ?V6F46cYzLPI^03%Lr!$mx^puk@$
AlSmfO-vG9DQUXXu;?KmNWMcUk3Uz!CrY&*Fzzf~sRJgYz?_IN!YYfC0<itklyt`|Um`ARRY)NC$p3DL9coTU$`H<JzF6niEN+!!
7}KYIY3{uw?SaCT>mPSnTtq!;(7Of_i7(PDzKWA_l{S)=OBQ+F`)45sNI~5IHcVXECPWIOQvgp7j!(|L_HLsro<HcmfnB-(TS3h2
Zs$~vHIZ3_WTm5Lgp=TocA%K8yDGdV(pWq=voy*HotGhQggSX?TI4pg7J0A8B3Txm^In=P9_Z&^ZTr!@C*@KyUJKBVz6%RmEnqnQ
q2Y~Fdvx=R6qS4m&5PXK01X30Adg^nI8*OQAW$S6&i)emL8Q*pbv7khwg{0(N12)ek|~75B@sJ3-Sh`iOM($jQ6AK$34h)K|4%b_
Q-O<g<C9{NBjd$M{%0Kn2ZN2tU60g0Y6Cq;3%|GrvM^S3A&S~}D5L)_s@sEmhx#3@s=isgSI=#oSW}G^NU9NV^dbeF6NY}=be%rG
M7U(>9YO)8AX_=%y&PCf95)o24yuw(RZheck8)ua-Vy(U0pT;FXFRco#sOafPIc*g0*6P*1Ha7Uzwk@$Og=WgQ60+|3NzhxG4FkE
GU*B%wpLV<gvlbE5JAAXC?@eZaS!|bZ=XMh`O=@?y?Ehn20H}~w}CSfoItqCQS*OTg3x$FxRfS65YE?&FmpgAhkdf<&M-i-u0Uch
fExT*(~|b(S4cyt4|7mPlCOvK!W2Upi|9CwVOAZS7H{46p7UQ$KmG2z@4ECAZKK|jFrUV;>)A6$7OlEO@xQd*091Gi{Lr$$d?xH!
6Ua#sAdp#VfJv(kY_sCkYVEHc49ai-T?SSgKfgAqnqJeB2wR<s88lAKGt7XG-&RP6JY?byhZ&f`5J*!C;gFt4{31GF7<R;(=aW%K
bi`qt`ma&EJwENoNT8qMrVrh0;F5J?vQB0TQ@TfzvW%7!TtrfTZJb_i<<kLH9OVFdg&mPsaXyRDib7JJ(cJE?^^D8*+MP9MK+Vdo
Acp=Lfx>b(&0na5+HuF=Fa+R+akfa+@bx+=`yyI^T@ik$U9K#RPoF+<08#stwgH09z!!YN9lcvV(LOoI_<C8_+S(Rj&eEC1s6*!t
+o$<F{sN*4@wmzoVArE?iMBez6I8sja9R+kd0O@Dly5`>*mH(TV6bNz7GZTp_zdR5gRq%~;Pkb{vkWqZA9xC!d(Nf+Is#IxI{(||
gRIF>Jj!ul9;nU{F8~R{BC+s}IXC=Kx5dD8#k&ABD?IFAf1ZCG-Ou8yC@)wr1vL7cEhpncQrKIM<kr}J;<1&*(LpI$3Qn5oOG%rl
iGLG4<UB)#;__$*owa6}E{!QE=0N>d6jypyYOTvKiRS>KV2<VleAlM7%J;xafQT<ccL1D2xJ8fDvKZ8N+;^p)^==Q5c8f|fc#67P
kpf*_$iR6-a1L+|*WuBNZ{dlt?eKsR*4%iQ0KyzvGDUGoCK#01y=l{Tlvv%h_73S*o@TI2hL#WN;1c%A+iXgpvVzqCwsRGs(Z0es
Vd?w|tsWvV3Gqz}<5iWUw<3WS#6s8_geUeBI!gM2erTH>Uc#gKI%kb}wFsvq*ee9dqbNb@5NT;NTr5&x<Tw%Hsdzd;kA!bLOY6|2
SvG3iZffSwiTc-VL_WXGg%awqzCb6J(pRt-y&}-%(*;P;fVJ2|jvc3Hx?9|6@Iwn&1_C)B{u~05c@>VXSsQm%ArfR08j|<1qsR4}
1E<ccVcOWbwypF~S&V`rm8p4tm<KBa0W=eqYl3`lE^G2>8MrDZ8aTjMf>zWhyS2@JCNv11pAQSe8o0;uD{xHasrqh#uG)^*D8Aq;
|2#N8|1kQcgCBwJ8qhJ_6LhAIVu1_scq^o|M@Ox4=qQ(L!`RSLO^+DvPfo?h+vafEqU~7oRb+hUoMkrXB=#3+ILkY-JK-!q8#_=k
lM_8*UXAln-lx6hg#^eCXS33vyRSG4n3!gkkf<mT`t;iRLu0gjsdx}slo_espS~U0NQHpm_Lt05TIgJw*}H9gM%-uYJw*;NwQM4e
`+}5NAQ~EM9_clBSO^J7J#w=ND?czwUAs|4g1vn}C1P~FEyCqw77pYS7A#F;4cZvoHs>Kv(`Vysqgx90Ng7ooIt^8p2F9NQRx%VI
g!YDO8=4~1LKgZ3^UxY9dd`14kBUfap2F8zsTDE5aehkj&_tPzwIOiS_|i@#UIc{}e!_Fm!<m*ze|dwF3ptvC^v1Na3*A<e`Ah+a
y);V7vF4ziG3&`9&aXQdx09kvtt)bs9oq5^NXfku79c%O0h@^R(RnyIl~|F1lSClSDS63(AHbwR<XNtY2cC}=-~#7t3P+B^qWm{+
-@WS~Vd*;SJPIf}%7ljuIdouVVF3~keoh8^d>$4U_d+tb2A_OUR}h<ECkso`o+0irY^D_41$udS8^()pg6u9yHK3*a%(W)!0|;qh
XnU3=PJ<ZTm--i+qAXY$4|cp>!~3x{2;eooETKq!R3Oml9rpWOl=bGhsET^8f!;K{<?ToFtN}G~Uduoj|3Q1y@oGL^<nZ*)AC3Mv
u5tODs2i?U5s0%hXSUAhTovIJoo0QGUt(JwAr)SQabme-X@t{r?tIGH%rspuW_%E6uR(l#P{?0%UuyR)h7bnwg2S$~j<-scd`Hi5
Gt$Lv)Ik&0v@mg3S=wrT&x&mxjbSw<Q`(f|ibg&FF(2L1YT10;hmQ5~!1Mv;ZnY!&M!6|z&vAdLqXSz7l>?hjZvv5PRWsKo5c&Ad
EnTmw<v&SB1r4ZkD;TXDjoEVeweV$pG1xcE>zjVrk^`M^2P?Q+5B;M3#o$eUj>C2EKV5n9?)1%X!RQZQX2$Q6*A24T1O$N_`>~4n
zz$*A$EQ_KuW{;X%lWB{N_m1@8bSwXb#4SZz&2w_2oyCh;>E%Vr$vK3lHi0B$`?_z>iCB?g%G8kcwWv*UxSKYnRT0)pc;<S==-LR
V?ZYz&|yaaKU%oHY4ds;mK~ml;Vn`0R8a&K1d9wF|Ly?kn#cD;IWB06hjTdO6X<OVEo`@~SVonm$U;7;<=mQdPc4bC0YL;3F)k1U
x=xdLvP~?$-z654e~<-W3KC%RQp?1q*RbM_VGUIO>zFH3!lK7LvVumc+ibmD<(<;~i6*H4t%edr`ZdPCBvm9<2v-V4Z8+B|J{h)x
I6-bRsLAU3BYhkip!KD5ngFXx*XSFF0d?UY88w>e<7wD=SPTmle)|pTBSn1s*%FQMhBP3OY4b56%$=11BwG*B%Svcv89LQ)x+<sY
S+^S3ABR^-3P*RUWBWe<b)yId$Fi&v$p^_3<0Gahrx7UfB3%JIBw7tAPBe=PhLDe}{=5Ke3_-aCp^^{^d-k1IPQHYVBc_^>^)(M~
IeIjQ5h%3)(ISgUTFg^;66c?iDM-C>k|Vx2>0(CuXqGM(XcJfI1{@qugf#<w<tpRk1LzW6vRV39l#nom^ZT3x1b`*QvFw>)V5Jo-
&3u7vIR<530DwK(o+i+i7J%+u70~~@|HHSRk~gR47?XT<`r)Ds^)Gc~r{|R4^qj*|TAN__eKhOf;n#9nct=F=zEFM=&x#O(_a4R=
>n;bi&_4WF8B|kH;>iyKG~@E;bw>O$ouF9CTR`rGf<#otnkkC2Afy(~bLY4CwLeB`V+Y8Ecb5ZmNjNVa${Q;OItOPD-55?n7Lk{S
o9J+y5)NddBGe__Rz*Z{MDf6ooc6J0h$qZ6SWtI{E6j3%{lufyguUOx#ag@JK!>A#u{&<B19dA-81`VPmBH~27eRWLz)=!W3lWVR
F&M`&bpQ3?_+q3jC}^RA$zx03w2tcdsiA{u5zFvTm=>9{fYZ&QTaPrNWt`L=t6%U+`r_H3o;R*V)0jH}^F)Ce=Yp|ChyCZ@zxeK3
ue!maPpW__6ya>X0HVxdmRs>O^{5JN1eoo7Pa&SYpInw1=-V`tzb?NSqY(x{w=<%rE}Ib8Kq5gfVOk4oh|=?mv5E*ARGI6Fywt>G
xb5?C)u)ZoY&yJzhdKP#>(WOup8ib(dmgHtYF}%C(<S!pTqk<SX?WBvajHMnLTh--eLUI8tOIRqoE5JZnzp#5=Uon-j}4m(6USf?
P9nyPE{>#jSw}@r)767BU!$m<UELDn;y~zu6U9V&SgVz=A_rsq$*~AraSD^kh4+Ip$QV;YNAexP$cUNKB`FN<E|j!l{N`lBokjOu
8ijmZ$$E*pLe!ygD*<FAAL9$pHzMy^0&bcEZE7MidV)9>pGLf-2_b<Rvp+$8!D+y=!Lwo~s_WK+Dae6`L*oqK)JKbSMR``Bm*c;4
5Ssp?U>lI?QB=l1qa+8e+><A>*5FV#PB@us&i^o%px`2)ENhB7B&n%~TTuRj>0nMkH55^~s@=y5TsIt`^H>50z3AnSM3zcW`1EX@
+$4ajpPp@O-sB=mP1CC+{tK{5@b;xMWBd&Be2rUJIDp4#a+Nzp>R9__q}Q2TlHxuUU;4fwi4F$SOrpp@>dNwP(bduuA~K0f0Cvh*
TBKJ*))vw13Xi5~XvDF!sRsVmhn4I#Goqwvq3t(H3WlT2ICV*1iTc!a`nE?GU1Kxa`1vBfx~8op(YPmR1NZ=>N(|`Ab@(Tmzq?4m
^RC$DX(IhDaFMQZEQ`U0I68;HShi}zUd_Blx>0V_E&4R??l#(P+MhLKuuIcBsX*B1rKt=-S`|`ZSf=4qtH>(Vv@`Z~AZX^$zUWX7
<f(Gym5V#l?DSkR6y|v3qK>rRcdocMio&aJyLAUGAyk)F=6OxNwrEB!5L#W0FLlI9*)=#+*SUCDsXt#8MHWxiMbwzMqb9ES#?SFR
pPVR@(C6hkFNBvYSMZz#KTuQPgrX7D31{RjNeO`>3~vMkQvKm+%YhHVGeEQmv_YgG>*8Pv>X_Iy@i3q!G>1K$grI)u^Xg(;;0#SW
C9mL<zy~Kyf>pYRr$p+>7D7n^aOzhG-k$YdKb3~n&;&S9#C<YUGdnN520Kb#L@OHk=tb9g(MK7q-)K2WL97t6fQ(U}UicyNKVW*z
&*pCah{JDs#UqZf!G|vOBJWXU?#a7mH(^Omrt1t=$tD<F_%aHSwJhc56^t5K&vv9C2y=xUhO;|cPZ`MNLzFLw6Tv>GOa9sJffOqP
TC)jCZAK+Yl4Gh>eui+#(kskM<MeCqDW4K(4jMbyZrnW*IfxTjg|ef3M{dX;og)y&>38khADaxRhOuP^rx+zw>C|7PtBN?T8*d}X
`-t0gazQQ0r!dnvGs8+iaRXGy;>LK>ImwOC9}8z~&2(VX*F#jQTaq`a#ZL?{JorzyJh#}pjWKAl+n}|7imKTg!i*&#)p0|VQ$q*5
#i&V9E<bf=#{NFK1{I^jOCp<`|E>}IM;@D<X+v8N^DKt#N2bC7gL%<IKP!(T#M%72CM?%zo#3tFbR;G58i`{m3`cFh<*Y^v4Q2Mx
4y%V8F{MP;vXw0-RlsXz&hSa!wojU1R2NX^xx#X{o<QW=8Oa@@%(19;6Fm$$goBb`@IRORF^X`=@uCK!rs@dw^0*emDQ_<a^v=)_
r)Vym79uC3+&!d)xk&w{B`8{C+v}9VS=cOx;u1a}XRxQ7?+N>+-Sg4A(VL6Y56;=E;|~tHsGPUQuYNf>J-;}{dJ}UOp1pb({0a}8
N9>0@B<_dPQ}~Tz)-&N;tSHbsJ$d(U9~P?(uV{x|p=k^=@6il$04TCv6#0R1U`Vvkp*w!P?>EY(jF#wJ98xDR8CB_po`Jj)VvHcl
mk&yNa?TzA5{b@RcE?Rgn!1mnS?2<}=;%rul{CTp8jxgoh%pH6udsA?ObPL1r{$DjcBSld^3mETju(|1{!Nz+=|Zi_UT7E9(Ve?*
ejUB}?ersVi!4D3N$8|Q3JQ={jG)S4-*3<a?S#`(R5hS-!BZUFui$iBvb8n0a%$4O>YMEKrKCmmSxjfLy))X~yH5btZeJ~bW_fGR
f8F7&-P<i|uOClKK!<CBUq-V5g~r@Z7wa4yCD#;CixCb)&7CB=69<c;j@5a<Zarbt{2HwiJyZffb(w$^6c*&IKu1LpCR`4qHlG=2
4CwS~64Q1-^5cn(K0kx#b&?i8qjq0~S=+27j%%O@#sT5U9qjlN&NW%t*-_^#p<A+h0fWJ+PsmDuqR->2HBw*vu7b{j%_KVAPY11s
s+<j)LO=@v;0>Hd41?*whn^o$(oqm>IOt{g2v2?bbJLszt_{Ww)@&l=c(}Z_!&mBwUQ?f@5gLt`80Agx2HQkSGDMc8Da0^YPKM2s
dugv;OV_UA0)SItyvWUfDz_E-r~f(`ec+wUmVm$nGGN150-febxB}8!5W5>PZ^DTVAK^b6=aGiqR5JW((6Et@2gHU*Ch?%qkPFHP
!15FaCqJJbP{j8Nqui)FXBj@Qo7^W(1WN_}gDi-IVQ%EBi2(gmS_*{~8J1Mb&LCC=+QO>s%!D%H`;dC=sSXU)7+5UoCx+pK6jzt*
<*qU-(t+u{Ku;KU_oMTz5f1aEa{=0Kq`U_}Nh&U{WKp`Ef$6S+$!76i94&$tL9QWU#!K9zc!K-;`h4`^_t9I~!g7|Mp5c>E&$_^p
{>P_h-iACck==wInQfYsYj<@W=9LfW5q?<d?aJs4x`W@tNBGac@6R_mZ3^HP{CD%RX{fIqjAEKn<e<pEE}30v57^$!rWiqIM}gmK
>dbvf$W*o_X36+_9k1LrK>(q9Iry&MANyjt?@)*X2q%u~na?tLW(tM+B!~}U2FgnjIVEQvz{y4BiJ}fv`GE{t0Z5stNtBJ8QsUPY
ub%SM(!BgXLGbI);AS{RDGKLBz-Dp__1VM=k_Y+bf%<3JdWA_<#6ootfI`d&Cba}~L0x3JNM)|rbi1**Y8P&koY8CTjDA0UJ34tY
da8s><}`F2#N<eu!&*50kxy9H`Q_{*Ndjct6+#LtUd9QvXb_XnDO5ol(dCSi#tIr8>@bBaOk;GI&Eu&<sS<o-c?_1InZAkS-Y^Ws
rij&@<+F7{?lX+HB3TBB8A!^iARF4@XliUi1P%Zknu$tuzX}m8v|JwDhp@s((iP|(8p%z|I0?ql%ye`&R4mwG#;y?59Zu^AG;oaU
<uExzvapKYG`Zj{o4)F=X4Bu64`k?g&77R$9c-vHl@hD)S<JdewSh<4a5<ylql%E&IGi{DOxDhjz?WvO!N%P-4z#Y;Xs8Pn+XTgi
nZG|iKR-VC#hARiubKU0660K0Y^e)^4TF6=!E^iSwFRtZX%L>mgN>{A{Qq0O+pXVWwq&4uhOK&sR=wMP?${>xHY<~rO-Zv=7I2t-
*D-!*Q?<LzVkPmJwt*XHA{o0DZu^JLitR2UaMV~9rqQ0a-#L7Gt-x(sL-X<5s@~eiv6)ovKAeAdNy4Gpjpo!$IH4{|ieBE!ar*~G
ScQZVl~EN)Ma|ftN}|S=Vv!Uv#HOIZZd=su)$fOmZJyus&fEQ=%p7zvvQvQEN?moSr0qVdXlCXtBdW}(q@nE2_N`Pn$bR4LUn#VI
BI{}FitwjA0Oav{Bt%g-{gQci08DxKi1z6LMpcfHNjI=(y9x(Zvr^gXqAb#KgBUmthdpo>`>o17Z%`?z8z9`9E!Z6=7`^=W$C8e=
4ps(osJJX%XHQRK3rw_pI^20&OAju^O@{@ByfQVXcpvUbTp5FZ;!v?1Z5=8_^G&Y8VJodweH%_3@gWKrq$(pgjO-BNAFc+r$j9{i
th4VKRFG82+fbzE3H)MLU_>*+&GVi0bWP_l6((hht$u3E?WyCU-^lv@0WK+;&UThkVTGVHzZ<>%W%Qwy6aI5Ded{!ggo{U4{E}Qi
gnwX-5wzR~>ZIdqf%xaRMO8hYfGdP^f4b&KWv6g((nJH^Q)tS6Y_^>WqC>Y*h=W(Lo7WOeBhx~Su3^bkUhp0mTQN<ZjZOlp*i8k1
%<Pt1DvVo6ZP|BK`^`tr2Y;1jY$2gv63B_Q5Y$WE_oM40x$ym+j_CS&k57Jo_3rqs>Wo6_DMCp?o2Uc~#~QU4?S8sIqxJHdWUgH8
q|`jpkImL7mhD{%+<WBkd|Ib19qtoZQ!C}NAKhvkaR&`&^|h+wh*G<i5_6lUS!`;%jZrda4JYQ!J$9Y1ggnRySBrGgaZC4e?<+W@
Pa;K)9r|XEez9DAZm-g<)+nve5>G}$&6*}Y-aZ7Cqfk(xBF7p;mxIHj@5h6^<#GMx-`k_+gMW7V?)c5WSwU9DHtg-Cli$Q>hur6|
?|<OAjt(9?4s3he>~3!hd}N)8vVc8~TI5rYG17YBV}U=3SEf?Pt0G>;e?^(UDxMq@<X&Z~6uDlJi@87riW6$kn@G=taVP*<87KN7
M`i|S+1*bj)$XROi09#ylf@M>Z3_eZJmI#2aB9?l2H$GiuB*?vlHAv0gkytw&Z(d7{++kD=bttgy=G2b(p7Q*B>EKqK`K&`e+fg2
_8WGW8~igsXFAAHLa7^Go+tv$6)AW$=}n7ZTak(M{GK8g85vY1ZN!{5ppH+LUtY~-F<LFdh2n%Il`)u;Bn&zoyv~T-1lnCzfd)(X
=i2Iou?GCtMyn0@jQ`ra<dQv9HY1tpa(5{1A7Ibu>77Oy`G3TX<e6EMTikQolPPN%ob{wi!xi8)CRbYiH0SjF@x{gHElBquF=1_n
KQ4^S%0uUU{Mxuzi5#W*dbz~Z>XwAddY0+mPrSs7JG4Sf?mF=#mRB#aMsWH*_}A%&-^fjPaFwO&Rqr-kte4TjW2Nb*XVCWJ`RD^X
reU-5H2ucEiI?c`K1k<t#;qQxLRm;&S?yFIZ6_l_!pXq?tL$oxM(;Cv)0stF(HO5(3W8ZW4Fc;^Ok4;;`KIIch$zCO@n8@6lCc@z
bu?^TCOSp~bc4#hRRod)iaN*-?2?$bhcIn#$LQn)?twJfJ_r9g#gK~a9kImSr2-bPbQhzBfS>?zfQQ%7Vg=hx$P{gHEK^)Y5;^M?
nqGQ2Wk>;DmX(^XsOSq%fi+Kjrtn=ZqZ#U0PkiYc4n89D@Q7wxyWtAW19TPvAx#%~wHMCj*SBI}j%;&S64!rLg)2^gUe7L6WdQUA
=o%LG#*t#=+LM)72fHC2N-TVlujgC}1Iyt*MexCj8N51LDaLcFGSqhytf)be3KAsQ8Ww03o?x(OVpc6*CiXSLZTXI?Z&qRgcJWeO
Q9&>mJMQtNGvm4^La5YHr5Xdx2Ab2q8>d5toazFE8G@u7VKxH>_yJ0KmGFx`lPuUX#hA&O8U#qdg22_e^Jq3de*pbrIl7NA6Bp^5
*HEGXp#!u?*Jl{ruYfAW#o~bg?u2C(77pQ(+bmRJ1Pl|x_+2T>OQDZcn&E^a|0DvIq}#5plGN1}0rahsK#NQct2;m^lLrO>9_R?K
2%=bp+Dwc|P;a-ulksXi-#JE1R?#feMHD9MmEaE+Hh{MhocYpOC(0BpAy^#IK&3aiW<(;Leu%_yxW*6^*e9S2(0=joDd7qmT?K?$
oQsK5*C|%PEC?!HQUlo5RXD{;7+DPKQN`o`vC0t*cUjuSB>ryk2*RY+`zLpnmdGFST2%>n=5rEc0$?dReP%#(k^_>Mfz=thgw)UV
WV&tjM;r|jBH3LlgtKc!#dVDskmg?Lwo<3OX0xm`*0oB7b*-vkT?u(Lij+}oZ=j<oDU{SGXh;EApHqk{G)i$%G(cnNtzEI$4K<Da
Mhx~|@z+A;h!fQ4D(V2WRQ!4pzPRTrdGe~Dn<~Lzhxw?$2-mtKhjZpVhb}z1JRI9a8`e||A;Ee@C}XRamxqHfSsBR17bk5)t#flQ
(=A-%tdxS1*tgbvjAsKaFN&&-Gm@*akoB;Olgh$V-9LEUVgH;CPhH15uewk{Yeu5DDmMm%Ff)WEysz|<>JiGaD5;$WR22pqU{Mw?
ur9B`HQ`s|N@aG~OLRTpJu~dEgkMsO;_!zt+Dy2GQKaH<>`9h>R5tF9s|DC`1@IpKL7U7S_EOFgel}MMtacOKN9Kq4v*kmMtj5*A
KSpVFRSQEl(5_8S&n^iJ<F5L}fGB^{Qp%q=`SKUe$Vga9NsHjx3X~_M&rzDk93~9g%B2|gs2QR54doK(Y;38Sx=X^!LyA{ak6=fr
)B}81)_T~En{$0F1Y-Si5?`&;b?!XExO^>IC4Z?ROmWGH>IBBs8u!d3N;=bZIJe6zDygC*>O{$|<6-TOb#~3o@oRTfttkD;-E~$;
eU=OmT|8D&rz&!rf`t?*<BC{l9Mo6X(20g#!YLAN6mPJ<9;~ak#8}rqx%B0H5#p80W$JlomNOyGM!1CjL%fOw9zQs!%n@ES6%X;t
OB9WgAAl_{9HArm<<Ypz;M`g5V^h0Nkvri6I!ZOJHR_mW2M#iS1f-;tJ-9qGm+fr5d}z;(pVvCB7)4vRo8x@#>*QE`)?u#QvYZ==
^eU&0Bo~DTGApk6t?RKIjqAk6ARRb#p!&8>$P>;+X^S3O1WO}=(SQNoV3dNVPpzklC{|i0<<f>PRE1P3Nn#iiS%2jFC~JGV|K*f+
ce^&&&~Wq)#<@|(4u0T5fr6oJ5;wPgMT*WqYprIh??S0ePxg;1D(ZLL#tT)Nd$0+vepw^2EREyE5NyvBBq0PViz}U@-$o_GI-CNB
HVKM_A83ut`4hx>%IqNln`sY`R8EJ{gbLnCs)J4oI+&7CPx0UwmqzYt1Y{8|R}=@2f)D3M<wk{!GPj6>iDHU@T~;Dfr|XO`ZRqIA
Vn8_N2MKwSbswHzy%d6FuJSXKYzaUj4NxhloxKp&^Aw~uTGugtV|6q{@(zurTj*c-evh)y2IA5-X_2wq;&PJPSam#aD#b<s<DGJa
3^&!sszFD6vj4Gbka~?JaDUt8A0@X&cAjw?GEdIPAOoR=@#f9Px37ZVkI#=^zZ(T_N53Dx8J!~{o&0|M_PGA0k~C4V<f1$$>G`+i
16B#7-6e`?Puo*WYB9iIT^l7tiKLe{$mml3Q9g~5S(p@g(}|yB1asGj1H_vzFU?&YH<Sl4&3B}twN&_^@;70A!x7>2s%rQSM0dRX
q3PneW@qRWW-`m@k|6^pX&A&md8?J3<{agH0=Sz!<a}=h3_{FCMr)g<l=7p$o3BvOUC~ao_|e*Z_3i%RW|^RECMuk;2A8h0-xcZG
r%8*uq`}8Z25HEyu<LDXff_rbpifWgtvsQUcaf&ZULVY(v4<){!<FYMNfT&n>yP$kG#NsaYKcneSPp}!Zqlg`qG8s-wDk79Q^!@w
#qugHrQ_4wbgx6UzVz9sLhs6gn6>I*@@=U)P0(e>34h0@CjmJR<(6M=tBaMuP=~I!sX#FhOR=CRI-?B>9f}6{sJ^bpjX}eV*p#^x
d87C}=(3T%n8|M>xWs5uiD8#MtNu{)X~VOxM`$R-R@xQ{R0&X7`d_X@%^K+C{8tqM_PH`KsNr}$>1@L@Or4~vXY#;2KHFi_d{mlP
vvqFDvel*sLLEorGj#ael0!h1uO<%=N#yEcBRgZ2eD#0-0NSU=G{BKH$1$H^)p@VZGoWD??>XXRuBHQMpFW+*Vw&r)sXm(KK`PDg
7MS60TT}efd8M*h(@YhI3ArjBz?@GaI%2S9subOJC?lLv5-2ag8Xl_dsFXQHPeqxVYfn%(osxV{H;Kpv8YH%q6NT1li%G`wO>qtl
OanPp8hYBMijtNT_cus{WzK0LNgF+ax+khh5FEO&8)yH%`1SPU?diz{6-~w<h&QKiM??3p!7Y3G{wz58_&&J!6;rOxsgd*kw|Di2
7^eLC-K+EJn^Kg$bb08rR~NsMl>jl+Fo95zMam8w(8l105<ATgDGR|uT4+^2k!<r)SwqmIdLpTEE}}p<E!N=z4kzqRoZKq0l+))B
{#1ME0Bvh|Sv_<TCm3a7o=D}=p(^_-{d2eNj#}(#Mh9#~c23a=tBmSBVvpN+e452qcoBiN%Jj?OQ{^qo!%5yzElolQtDde4bT7g8
s)6k2f_un0zf`?!``92y%6O#*R2^Eub6=v*6oFl4Mk4~KQg(d*PhQX-vIowftT2R8cp{JR7FcI!U>AosHB4#+2TdP68$k4GkH`fI
gTTh>LeD~-YzdDcG={zbVJQn-s9`xfJ3rclB46PED$Dd*Zy47N8S*M^r%w6t4h++1A_iaMBuvR+49cv={;fKzIb9VVL_h=(t|)sz
w=g_V9ecJ$fTP^{3ca8$InRyn35b6Lr@whMqngoGllue(65FFu`F?+^y7&2zrTRw66;+bK+6jD1y)L)h4rE;_T-K)a=F-kOaAql)
X;VjP2NG{1GKcKx0sru)^DE!3VU8&*<^C9^Hs-9xtytQPQPI1ZB>pb#9aVcOUSQ#URmqv^z>zr}19EZ|2Vz{SLB*L(^17cfgm=Yg
D2#yGFe5O#+bLX#U6^a!yI4283_s`^*IVov?qJyW(QA%>e@e{aBN)MeBpsav6skjR7!dEU8WFkq)lGO@HH5SL=nA}Qfoh7T38+8|
IXTL>l7Nl(Qfb|IVN@8b1_8NZl~E#(alK#}uVP*yW!$B#j9+D;G24}-FGC#?M11vIkPLY3OyQj_hR3%V51kIrm%W(lm9o?8fOqv=
q6PET26&X#8Q@H%h3a2Qsg)TXSmzl8^@m!I9Fo+-Guw;sG}38r?v{KD`jV~s?8+EABg$k;SH^BM_jMP>Mek}21Yzqsmy^}1_aA5$
q81cw8Ii*gng^2#3zDF;r4z0&(c{XXTe<=ca#vqIpo1O8s3REPme+kYhB2y}*tyz1hqCCjC3TyKsy9}<*V(q-H{A)%C{>o#u+t?l
XOJ3fE!tkoVsDPr(HB!vXq@ZS3<5G#%binoQviWfKH8)3A}gf!4Y#ObepkPygaXEYQYz@~_1a65J7buiHQXs<F1@2SPtw-pqA&`V
q<N^YA0RtKXM`MRKBqb;9akVL0y_vWo}O;4{giO9rh6&jkYja|lcsCpIJH(`Ge*T<Yd2-N>aL2~AcV7gRXt6*CzRRlcoG4AMl3)u
Eq*YmZ{xjOSe><@3@WoyEPeW#3ZPEiuEW=Ck|u{fXRLsFHye^zup`Smxg8RlZK{~sR1Wp<sK292P6tk+yC9Fq%2T;nmltMKK;0p^
$u5@nOE+v7ig6s$tL{E49UWM)5{(cQ;f*&^CSzA>t?UN=AC*uI=)Y&D$0rvRF$76qmt!G!iXddm2+FcLR1*hN%J58!p`+4Ra>!I8
BMlMnJEM)8Ns$EUz^8vHON?KO&6|TWRiKyKIv2hI<}0JPfhiIh<8V~+r$hqo)o`TWaz>sihQkx~e}UfL(2LGjUp*o<80c$-u@e@i
DpHg%DKg_w8WyG8E#g%Wt@3!m3<_kd3{6S_I*{pFm{mHx2H7*pf(c6Yn%OPGdst;S3z9Tja<bqpa99iiHTwhJ6<}J2{t+%#*I^~w
53Pg`uD9`My#N+Y&NEgV7_C(kSt>)Q%hCJll0!6CFJ`n%?9>RorYcgE&M`(OFN`rb&X#)Q!|X}_Oqc@fgomb?uzXv7Ub(ZmE`fqR
q{*a;;?`fk)V^^-5F~XC=T8yQ^1E@ZPmbJXGn&gwZ=%UH%}9-FKqR-+Bq63zZmUWkbG}osG&O><A_*iVw1|h$HSF5R*>&EWeWdFU
Ek#L+fjC3cJ)*?r>ZMDZ9m>}(Z9kLM5`bkpREVe70ZC{L9U3$QpBt_WZS~ZU@#&E*ooq3oQHr{#&KPINF^1dY3ma~tBH)Z`0+aN-
&(&cl)kt%WPTa#KUd9}1jFr2sx2gV|go*K#Lp4Ed(jz8Fsa>cTHHM1Or{h{Gi;_m^V<Vi&G|%p_q;etb`>jM9sW2pSEkeF4H+T)k
wZy0TiX`}y37XsMaYL+8)4Vz|BXQ=;-lZU0)+ckSF0ipSB$`R3d7=*IPMkvPCzcSV8%dA#t)b+z;QT)J5}{cjw{&ng^y?K}(m^ND
FeJ7bP^#su+KecMHND#Ho`w`FwaFsF6v{;wD<Z!d(&RxLIFAg%)@zzug;om6py_+I<XRQ1x@H<N;*>YuBTWsZT{}?v|AJt<Q@Gtj
z-6R50WmI{#06b<Yi!g3Qq==wG!b3qgit^?1DoZ{`*8i8r)2I{d2?M@E;sb0;b&`M+BV|sBRH3lDs<ZDCN2?4O2*Cim<Q_qD`C}Q
C^TL5cnOG62~2L;XtzYNnSb=h+33UZ`_ak8d2n+2b`%`HMQNhpZVtna5OlS-V_O|?b%!3={Y;O`Ee8i0WxsV5BExZ}Z0<%gbP-c=
H8VhpWDcVdPMKR#mF^nOR+_g~9H%)oe_pFEG*tD4^oM2mwk|SMquu5$Zen^-a8=xGXLX-052v<=F0eoesxc@8y_Hn@N#$g!?bJ1q
a84Voiz0qGJ??Z@Kq32IC}55&&(Fkftx$K57#|$HBC`gZyQmI;rtVx-N*V2RIGu|5u~CX9!a5KZgQileE56SX{tYl)8~<j^v1Zh1
LQ>D(?-pdz_5bW$r<=U6_=MRrXbu70sfks%Fq*Wee}wjRiJ(-=t_)9skHevUO<|8_<fYua+uV0$QrH=l1nZD)MOPehP?3FgA@da+
sm1H4=g8Cf3GZ{UqCxWrB#RmChD2O~l85_Zyg*EIDF<I+hgg^_-9<60qv!pmi;3teW={T~jC7(*U1gaH*r;q@yH(YUn#-@-IZxaG
#ffbV=<W)sq)|>u^=~|C?uF!e<2&(ml-D<v`2r$TDiTAMYALHzdN6k!Z=GtaKgJOyH_33K6zKPlix`gXUlI9TFm9GyW$V2!*5QpH
M{-m4Xyt0_)_b@4(rt|K;NTtUmdu>imNURw`YA1Q#`hg@Ynq)X7ck$dT+6UGY@)Pq&N<5Mn{<dq8pb(ACR^o6z6cj#Yh|IyB&tf@
j+kf8v!OK0B!+n{9`r>ccv;3Z;n-|zFgsh~6)HDo&+y#jYO<AeQ#lF+^@KF@13HezAXWm$_8bdi98(<H!(GeY>~PxFI<{jRfCG^Y
FGVd7<d*p?KzD_!LkCm?PBGVwuvS9A&vpj&V-+ulK9fZC1s+M`E}LyTM~;*-o!&=l)_DP9c89zvIsR$dJLDb(4*N8&p9IoO@9Ypm
9f>!S02d8`j-Bq=uhzN1as8>>--=-xbU_9jh*>?JQ>T^MVW3ukAsve5{L@{EwSt`bT3rOU%MxP1s}?IdpEX~aJu`vIxJ9sI*qYc`
iOFwEI4B#FR3~;fA5J>p@K+rPc;%Sy<{*1*_VOA=RuO%z5yh3Xg!bMC4S=h~qSqsUMPROm04q&_H~%w(a=o^(?2=}5;dQ3OLdpiF
pUNCaH;^9DOZB1*+hJv466V(w2O<A9Tq%z_k^0<-2Q$X0<Zup$7Fk9^8ClTsgT^cD8x8~Sfz+We*^gYxJlsP~t$h|~DR#(pfd^ae
-WGkxP>U)BMZMkSB{^6!ko(AKo*UDab*gSJGOv6@(WWc`lP-+tJz;CU^TzbKnLW}4*BJkYR<cQ?joxNdAVuv^{@z`@SV*8Ja9)uv
3`<5!bdw<k*3bGrc7Fpoy81YJwv~^*a>6-X-koBgcTBU)7wH`u_HGWy>W{mY`_3yx8ASy|IGFuSqOx!ybc$C{sp>ICO)E#m<v4Ny
A!%_r-~Zz`r5o<1eJT&|3DgSC8{XMAFqnp?uCN2%LNrWzm6+%avY4IUD7vRU+QYKT6Gh6c0X$o02qXa~(DEi`^b)0S7T}P;F#eew
YJd4jQJ`{REdrb7=yjRRX2I3ojrhi9NvmC4<Fr3RT5IfeABDk?_qkpeg`vCU0C{8A%?b;C#BUlu+D$vz$-%Gp@c^(eoyw8fS4<I;
_orv2rm~|j7TsrP?)HW=?)5{?wcl{bFT_)<GlkUx8`T-Pi?1g5c9i_nRZY&1f5DzSQ|{!8y}MMdCRoB6`R>7n8`s55&~=P7ch0ZG
3Ds^{qT8-6G0{?=;5msdBGXk<A(*53{7>g{KBN0o`2YKu<~6R0e0e-uQ}BB$J*tTSWNgE!sT%*f7rHurTiGS^e+`$N8&^OYU~8Db
-Hr>@8?{ZzPqD8Wl<*(f7s69`Foica$P?47%(mqWe<~Y_vGi{1#7s13x=Bj;cQmeJ%psyEZZg|1Wgia8dLfA_Hihx3FH4Uw-&}wa
HSUS${5MJ0YD+w?)gz>VZX+$O;cMqbB^?*HBws|)s<Vufj(>#FUiVl&Ol^YG!!Nz6tj&T?Y2y`2(vm{gE`)i_Xt;-+wkq;nVt3<x
^)AzzEXgG_rrda;dN<5af-Yqw`m2N`3#PSjJ|e^`5N8sQpD@ZBMKQI{uBzJtqhcQTZJ5P)ic}?pFF{3M{A0mQQ%NIXTuFT?sKdzW
h)EY{N3jLFe=sjz5)c}5<7?Il{kpOTm85xX#4$d-EQ=m}Y0JKR{jmtS9PG;1IO|NHu2BgW(+DWQU-fly9o2Wq%~cK6oaO0~#9H=6
G<;&PPbS?N3*lO?oSx;DOEN`-nvD)6eS^~}7;2(`#TV(4XZ8eB^;o*t`5MEB_y$RnPBn%wlB#d9%9eV)0s+fJ++HdWi}*aL&hMvZ
+Y9}=Qs<Y7eUw#x-IgN1ctP#|gH?WaR`}gn;J0~Tb91)$Aq-A+Lq3(VpQGpfJ<Idj)(<)Qedk9BWaCk=*!2(n{?5Q<)tn9&Xl9eB
xQl=;_6eV%2S@o~>VYa{Mc;iK3!mv+0CJD&3(}U-w_tI8+ks-0tL*5iyhi&aXUZrSl3s*F0<tD-!qRpdSsHi6dt{vN+7(ges_hG-
jCha>9&vQPilIMmOTk{5elMJ)S)pq6c1c1SVmNAEfYzL~2p-%^y}a|j-`j<NRd~&`Fiv3C(Wh^iOZX}cQW7i}ZuBDf`Sin^(a`PN
vBy-Bm|!~wBD;*tVqc<V;68$K(O#1l<g#+FsuyFs7~Tp3GqCsr^lLcbOcL+$I(4+rz`Bs{H&Sn0=Y2GVRk#O}I5`l@-K8?&;fhVX
++}w2xL)*FMK1l#BFLNn1H}mev;
"""
EXPECTED_SHA256 = "e08e0fa157b4f8706b003d907a338ae608b35fc9517bb84d05f3ddd4f8b35b94"

def run():
    wrapper = Path(sys.argv[1]).resolve()
    work = Path(os.environ.get(
        'OM_WORK', '/group-volume/' + os.environ.get('OM_USER', 'minsoo3.kim')
        + '/offpolicy-misranking'))
    candidates = []
    if wrapper.parent.name == 'scripts':
        candidates.append(wrapper.parent.parent)
    candidates.extend((Path.cwd(), work))
    repo = next((path.resolve() for path in candidates
                 if (path / 'src/selector_pair_gpu.py').is_file()), None)
    if repo is None:
        print('[handoff-abort] existing Pair checkout not found; run this file '
              'from the existing repository; nothing was stopped or changed',
              file=sys.stderr, flush=True)
        return 2
    raw = zlib.decompress(base64.b85decode(''.join(PAYLOAD.split())))
    if hashlib.sha256(raw).hexdigest() != EXPECTED_SHA256:
        raise RuntimeError('embedded handoff payload checksum mismatch')
    sources = json.loads(raw)
    for name in ('selector_pair_diagnostic', 'selector_pair_deploy', 'selector_pair_handoff'):
        module = types.ModuleType(name)
        module.__file__ = str(repo / 'scripts' / (name + '.py'))
        sys.modules[name] = module
        exec(compile(sources[name], module.__file__, 'exec'), module.__dict__)
    sys.argv = [str(repo / 'scripts/selector_pair_handoff.py'), *sys.argv[2:]]
    return sys.modules['selector_pair_handoff'].main()

raise SystemExit(run())
PAIR_HANDOFF_PYTHON
