#!/usr/bin/env bash
# Self-contained owner-node handoff. No git pull, network, or extracted helpers.
# Generated by scripts/build_selector_pair_handoff.py; edit the Python sources.
set -euo pipefail
export PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
export OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1
exec python3 -B - "$0" "$@" <<'PAIR_HANDOFF_PYTHON'
import base64
import hashlib
import json
import os
from pathlib import Path
import sys
import types
import zlib

PAYLOAD = """
c-qZ84RhNzmVX78&K$*7qU|(kcb%#?`EVOg6FU<--R{{M4kbb|8;ax-q#f0(|9<ZS06~iS=<eOjrBmA^fd}B>eZL1hK2b82vnnsc
B1+0IPNGGYt16j2Iel_V|9zBEJj%0lB}~&1HWg_;`z+*r63c8RUx-ZJ%TlN+FGM7YGM`DML|zIRCl$OY>nym<ZnLW@%HpVuMVd^@
s9Xtz9Eg`fEu%CQr7ZHY5{VKjx|gxY>q@~0qPmkpeko*`EM-;+mBX7v-Da~W6G^5Dn3u@YSj_UQD)Tgzr4kQGbqD=LvP76kw!rBu
lSLWP1Av58%**@_nL)o;;{15c8N6MJFr3#_UCJ=jAVid9c?G@mOyOG0+j3DvrIPl=e3n(IefnMHP1|Ku-Pwm+>5&R}3-~a@d~h2n
K(nlx$9k%fYhP7zS<I8P8NUJ~;r!me{4IR-_v^DOF&58`|N0%iyUk)b7t_3k-|?W5Un>9fHWTo#j2@sJz6oGQ0UraOKO}RJ%4`7N
eeuIsSg5)m^_76Aj5_nnd7f854r4L(Zf~=jpXw6OU5b3FWO>gR6!|i#DjB~pn?8$*0=7J=#53_r@+z1>PfyQ{;lmVePMcMYXkI*&
KM7(<vzBF<mul=KK**)^eDRH*jcMRFcqoCkL!!I^?!geK5+*hN?)md?zcYA2GNK&{@&bnQ$|=B%l(+*zPNjo{II1F8F~1KG^nk#@
1Wwwh#FoDJkw<gU7$r)IU!$~^XSj-ix0F>xa1k802R@id3A^X{E#zRcW@W&gQ5xnC8F0b?S#?NEX%?k`jA5?$A;7=wUIRB*NwtD+
gIop6=y#X}Hh@-PEbslHz}HE(@!CAWCk=}S2S_&)LlmVb^9Nwq7UE%A;z)Qn7v&Ab$?>zlJpcYXzq_A6C22H+4GmP0CRLhbQVo0u
d-Fu5F^&gga2vBK2ld<t2wD6E#ep~a(Zl)ZzVL?sy7_h@{$nh>zkNKvKJ%PG@E;19B&%ifwklVhHiWsMAWRKm1Xu~oOap&D(ev|8
J-^+rNMdN0WR;%j&9jN$g<Q?<aDT9o9_Hjbe@LD5c=nkF_I)uP+pTS&At4o&LvMT62}tDOfyQa7KZ@f{C*Jh{c{z&*(56kL3OF4E
kCN4ZTl)UZ>9a{gxLUe}X*88g977z*Z1h*+O)fwR!{myUnAe~)K>ps7rpfM;GS5zhOi0+w@>*+z2zI#6N|{D5HmI=~OhyHoz4MZZ
W`iPCRnq*CIA_Zk3C`O`l>-oW$7WBF-V<2Vmm!UUbSATUDM10r0gdaDFW?phKYj3nELuwJ@aVM_^rEPPVg+pCfkq8m-vV{#tvkCh
2VIyypt>9LN^fXFD3T^PqJ08}K=$BS37LW%^1Ke=!MYJsk2o~W02p7Ud4YdcQdRhSUP}3g#J>u_OjOdJGE<;NNBT|d4cl<-KQGA=
hQhyCFW_G&Txt{!-t11!K96t<nkSe}221qTZMd4^=H6omuWMS$__09_V8VIG^il~6w@>Qqa|X0}`()kLMjn#XEMH{FA3#-_ZeNI)
=`&KQ#x1M_&~ctEl&Esi+ApsmdRH$FO3+qD6aB?d2wNtvSZ@of7OE1=q*6uc(3(3)$YkFD+JQs?QobO`mdbd6tZ9rK5;wr4OdU5g
F3>t+Xef?-B40y>0}rgV4A4!R@Q+&7as&wd4Dj#;N*UbWd73QlD$myfUrCt_Q5+-L91pD`h+&GzPH1m{tr9GAz*wFovjJ-Br<yVE
z^1ViM1h0gfKH!+f}rP(zCT#Vu3An?!ue_lUyBMwrv@4ndC^f3wsDZCP_32#>vK!V94i0GY5-NKz(NI}0}GgJ2av>NBGu_8Bg{#V
0X&u#+nO2dif_i^r2jLlhFbi{2m`nq`1*0&hp_IyDNxkstz*z+cVTNc=C(mYoH0upz-s(c1Pr+gJZ>OuF=}_D5C%s?j66y5w8+zB
MiO*Zm-li+GNi~sTM{W-CkM%!q+9}fSfahP-Z8YpOh)$&NbK+w(0=p{0ir$V_k)tDMFPzl^fpM+d{KgE3DA@9a3dRPYFf2<va@=y
=wpQ>Iq(>YzYC3<)ZG1dk0t{!62c17Jc>bTHTtu=?rn=T|LP(p#SHclz^VoWJy?K=;OS2u3Zy+y0CBj-=wSf?%~6-gf$s0`S<imj
v`PhpncZLweJHvs4#?I>?qyizBv)bYX;r%xq0O<u<rNuYL&q>1itANj{(M=1RG8KkKkr-G=CbrSdYGNE4OFHqX=k+EhRYv{&vG?R
qvbS?5Fe-b<K}n*k{)9KN{+8fSZPaF8bD};lM@3T{zVQNfOM?>dUHzO9Aj{XuKcXhDiKxem{9E<;ol7vlj<7tHW0e`^<AzinmfAC
NKp6!`N2qiaw1Uqc~@ue&R$<%eiR>Go_`eYE?@s5-kiVu`Qq~G`usJJ-`s<DFW-f4;e~iaIBR<Q@$wR$am@9GUE_T`d--N`dGYS=
0W8)AMKDHEpx>M2<bbIo;O;uD)R7~Kj%F}~5;O277cveuVZX+<tncp=1%?Bm6efeA68kQngCr19irl#}hLZTO0!(CPLV>5%a+~ih
jIk4R2mr+3##<Nz?S4d|4}2Jn)EyAX_~a=*y@jQFKoa28Qw#-WTGSO$#&AC`3JN7~Yf@X#ef%vz!$oU7&_JPGG)y`7UcWti{mbPi
+!nnA@JnNW0KduvG(J+H{lo-1BmWGHlpdo`kF>#_4py#tif3O65X>!U)0$f|H4WatrdZloXba2>$ehQQUf<4;Z9%U4o`}SDVNM~c
V2(fr+-<1eA?b%#Z^b{|=ZjYzxuucu3IPB`onQ9JlFjuaw}ix8Q|u|@QzTCSmevZSB`|CXk^l%31PL&K$mD|{#U_km>&^pq>rafT
?$7}N_hAWQI+=of8C4WX#2{i7Wfd{y#(ZK~ffQ;YE`I`(pDx<u^Ai}g7kTv)8uDG7ZJYHnQ3{ZJY6Qj+(a8hsI5@Hqh0s9mCi4~e
Ep<jNF4zXqLXs5#5`CU5YLvd%uS3q7n#m~rGCSSMRLyMA>jCEjkasE`D^N=V=;#Mwh=Mf?*8*JQEFV9@+kpPG9MmR78y@NjRgoa4
c-1!MYjmUE2h$BXVVnXiKmK;Q%V?*V1NsN87(_D}jznx|(tWdXL3>6E08K?nssNqQJ^X?A^tNLE@^2SsA9*LsB@i&74AgL$0Z^4i
1&H2?)ZLhM6Have2tU^1k%qRLpv|NWY_y4w2gHUbCXrES$aIC#+GSqJql=%ej&R3S5zQon1KVo_I7w6$kS2nqg8o4jL~aH*3d}@6
{u%!de+-<UiM6XZD9hF+ZeiC=cCn1~J|?Im1Hg$5f{I1Y&oM1ArhwsLG@eZaff#1=9K+lQ?g#PRaRcKkaSi^jG_gXEB%OG6mV%GT
c@R{(H7MCK`GdZa^PeoTC=DC}1RaNgJlNk?S7#r8J$s|Ku$krU6MS>~WC$whziyxSYl^eVb`yH#w()wzlvmtEs?(8PVaE=%g#!)1
!SnbLew+r!^R=Q)0osC}>lb}PeIr06$r<KpjO*f2goXBiLrWaN)8s4+`u#p&-U}k8rZp)`rr*1y@U|HOh~1mh?~jisfezAPaE=03
!t>pCrGDocg_aX^xG@H|u#%$D%%{M)=$4{A73W|@Vk<EFC7_g*8t?&r)LcsXx)ZWDX&9PU@H-fO0~#EoAoR{jRV*X;YI72x4UN5<
t3XFSnXWJ2hkv{L_zPL5M~gDAi_v|a)=PQx*lBwE1loQA%H!Q$f)32{Z-dXt5~=7YpU>G>9)SWXBU-9O5}AFN;4#^+;AOd}F*)~v
z6@fiW?*e0@sGnW&SzoR>Ka6G97ej&0IWw+PGIeUMj;~~z2$iXcJa7(nP{hnsFl1SMQRBpN5snNsFkT4-Jig;{XL^otZ@X6_4YXg
cR9)_4G4OprqS@|7eZ7<kg>%JEsPU`9|OlbDN2mcbF(2h>+#s@*OX-MnJiy$0YW#vmYC{`$`#rZ1B|>SU&da0*+_9C#7;e@uR-;t
@(wb-o5<OiCr!w~n9Ptvr{2TV8)}}==J-|vROiDUO7zEhwKl=nVR+8@YP#0_P{$y*syw~7N@Ab!!l<2lH+owU@MsQdR>l*7mdV-`
8=4!Ry4wPMX*STDey_#g5d-Ai1+2w%RY~<iD2WkCG$pTpyY@Sbe$0FfLeQ8=q;|p(xjGCzn}Wss-_=UNW}kgYFuj9J53rsLJBfP4
4lt<A(!WK`<=WEeO0bD7Qn`p`D?n;eI{9(bNa!lYiPGVOm`!a;(_gTqsXZ=oNnz_FSb<a(I{GsSyp6G_X&nPUqVtKFegHCEF&ge<
S^#6*W|vqy5V47xu>1z&#hD2~y9W_^efIHvAkHh*NY5Dv)T}Nv6=BjFzG`RS1&Cmb^Qb$3$||4LGKykdKaerd|E<(M&KmSenoJML
_8*qur+sZ6$x8SW>3_9S8<~H2M}epSM7k`i!7<B7;wxA?@Bv8UhN)0`fgD6aqv>v|2@w_xB+-T~(|y>ohK5c;tx;m^e}&fKC3D{>
wPempa!V|knd2ikIIu{a9tXKsD@qRt-9>vj1j#Vr!T$25NAU0X$p`t!T0oEt-H=Ea|JcZkZstUBr?uDOq%E~MZIj~dQU_F(Xg4+)
O`r#z!t@2E;r*MFNjr^RQ*Jr~`X@8Re7re1osij1DV<Jo-x;b_?qF^be?uoxm=H&(qO#I~>rY91YRwPr#o&xk{%0%7hI5D&6Zc>(
fK-Cd1I}Yv7otw$eMDtEG$(Ht!C;tDu7SY4M*rWVrwK#Nm0lL*7->M0@a@4xlS^g<PB~|cYr<ZWmgac$U@yH>+-}Z;mK8kd+JKY4
PB7ETEu5NxlZmgBrm|^#Jn86u4_5%+@fT)89uP`1OL%NV1nP(x2ju)N82LrI9r1BXNA`YkHSlZQP_`*e&>MK#!T`OyAv8>e=7|x}
JkwH|N1S}~gfnu2$~hUOoa&}nw&kN-CG5(<wsL0tfE2#jH`M3=Y|^Uqu^@>mPmoycE7%dryhFbx^}d@n=bnxQ5!ElJ$)e6{B_3hi
HHEG^G3JgL!W97B2{@?XFcJ&&M$QZc$KTPIG7~fzpiQCFE~{wmPm6cm&EX`K%k2e)sJ(r>O1_|u(k1MJMJBx6F?b9vz7k}Ra7AG>
162{#nAt9wqX9}ZL&1&l2ZT3*b&Zx-PV+kj0mVFx7O3q?121x`OUUJomH<Dh1P}@uV(4TLUG>#+1Qsg;rvd}0<+;#uMBO}{H2KTD
#TT722n$4)G-*$3qtU?S9bjbc1fry|6R<xL0ZH_7cGO#%av<Pm8-P3UoUPl<u_o(tb3qcBoV4Rit22`xLA%)GJt(wc=s?d3{TZ0n
*kXE9_%!^1PA%B^QC1m>r^%RU&(WVBIz<(a>meuzY@!9&q^GvQ^;<~8ZYfVdSyV;pGu31C)F|OMki1}omzX{G4@v~gU?wpbe{Bna
hCwBuzgk_@p9a_!)ZU$5#Wm3&xF|E)wrT3ZIQqLMR0JGkLD5cZ$&7AK^lndl_lvu2Gcj@D4ZIA+2L|vi&p+42&IIoEY0~0uXz+;<
v74<r)d)MV##OWc)7Ql!TV~Y9kyW0fU$}Bv;{Z)W!!>-B<ry??tN-?9^x3h-GC-SRqM5<97Kkf!(8w(;ZJAvMXJ<?SqqJOLOf;IC
g*s;A`Iv2D`qosKwh@a#QSRGlz9|OqI2(O_c@e(8yt)q2T>&x1ZEYzB40Yo9>kbw}?Hp?o1<OD=4i*Ybe6_i*$F(EFNOU<F6g2G;
P8j#f7Y&(QPEzFwTEq$L(!W$Z)z59n`*wtG=m=)en1&TfbkueK%@O?;d5Qn*VxY}eE(P_l*Pr5TcqdCT+44-kaM@=!Zu(ip<fb%T
Q~a{UH_fRHH|S#6(dmYfF7VbRCUrP#L7^{!5f+MbWL3LZkWUEw`wZCT9@l>&V_djzfZCS+rp|zdKoIbalwltOwz&_czUggYQ_Gqz
BQ+6^7MkJjwh{c5c!}hZ#8H)(rv4(r>P#wjVNMLhM@;o)`pk)-qzjWINM67-yfolaOgdK}XTf6dlns7?K}s$XCg8vXC^6th22V3l
Xl=HbV*c8ygefC01G-K%S6S>?ml)b0Q!f=)MraYyvc~&F(%Oy?aO`dH`qP`2;jiac=da$Kg>TM&J%4?6HTGaPKK%Xq?d8Rr%ZqEO
r^nM9uP@)6jlGkec=YA_58=h9_u=(hET6feM&kW1?>1jvemJ{$_3q_W_ls|5cH{BTA6{O+B_j_h)UjacbV$yzG9?Rmz~yj$q3H;w
bw_<ct4)q%mxUPs<N5bpj-)ztBmwX`>L>-~gxyK9`+UYZLe6#~{;9m_2wfv3w2>T(X_7_ds>P8e1bA0h35D4XbG@j=fl&~kR#fL8
7-U(LNZI5k?b7jinJi$gsWqyPo8fa4m{ieJ4NOZ{5W=cwb%oJE=x-Y69ZeYmZWX43^~Y_U9dTrQ4?Ca%*eW0S3RsnpElmBMKmssz
xFT9aSSLbz$iYrWvceEfZdb{uq+=Qlb#a2PXHo?)nq|E<g6Pu$DI3bFVq>kZ%gS)JPL>fF18g8zu25uY*v!uNw_%ZpD*%^ec4s$?
Q}bh9WjiL<blyW@mQ1w2?r_44!tr7%E%ooBx7Kt`vXGDnC@iQn)3$H|h=cZQG470!agc&o_|98_p#U&InpT9w-@?mZ{0%?X0o51%
LW86okm~e5JSgJ->zJhyqHICM8Wq;_le)Ku7q%nW9=y?OV+G{8$*16xlb4+fT{BI(jl>+PrxpGY%;t-reIf`L!r31u7{!`Zh9xg<
&_tm+em9H6Uv+z7%Da*jPqLYF5mahP(Gbi;DwF?mPL(43mUw0D*=KR_@H%YBNFH|;0kvU8;DXz0TySHqNCeH}xtX4!bK3L3%#stH
!K4TNeVe%jvzRPGk&dyR+sq{SD7BrGfqB;02PG7n4Y7roR0o8WEIf6N&ep|9x8suYVe?)m)z#JpNMm&g$n3N*@O2rV%}tK*AP!it
s||>po*W@Dk0g>Qu|Ypr%9`f|26r)9w*jlksymsk9iW`lYCo)pD5*w^8aQR=I+xR;82tm9Md%*Ljkd4@?Ggc79q`7S6WCHBpdm3P
N1PS2XA8_xQBz)~$)!2T(m06bm=F<yBb;~_o61)F-tro`!LH*Yn`dJClYYDslbQDX4d+x3MVV!FfLlr^)twHgvt{SVJ^ah=&i9*V
Q0XM~kH#I^zuxxJ^!Z<wtv%<1-K7ug<}vPlF2e|^W`X8mGKj$G#M+tzt;{t5n(RN=Eg+ggunX}t7>W$8nDB0NO~S++s<)y<$6#Bl
XbWj0>+z(=JgwE8IYZ!i_Rt;H$oCYZv$Vwm^jB1dK7*e)Lr!^9R2l2gAL21-j@`x-NZ~O_;=a1|zM}M#r^kCh5=O&JK7>kAAizBy
L6zvZFsBZEk8;<@HTdksBWijscX`1+rBiKzb;IbVcJw=MqMl5<UcR#>_#YLrhxGHq<@v>RM^m9>8ggaAUM)rLu0F{M^9~oN@)sre
XfRRj3wIiGS(<I+9Gk!!A!y@bT?DKF1oRt=vGivh7Ufb2lgjnB&V|q1e(juha<!&24p;2lX1Y4e3`Z^yS7PJaX2QYG0R1(67<~Qp
BQoi!0F4z@K)eWK$c)=Qjj8nmdHSJB_{8ljO^Q$!DoI(zq+pz5)FH%VC7r`9^4T4jC$bEuX#80{vy8sLDx)~e@^XnSqxc?lO|+0L
c%V{3tOK+UQCi$Z_8cxPD8xY0%JbJgtryTTt2!$Voz|v_UMgc~NVRnVT4tDV!-!@Y(=rjLQ;?)8a0ENRF$<?EXAG`-A&AV(zJ||%
ln{aN&@>aD%Cws9=A_cL5-kr*W-Gl+ZIkW&Ld@zCYipQtQET<^pAn!<zsUwnu4m#%i^ogv6O|jrvl-XHh-z8VT9``Jwx&NRzICOE
Mu9!6s~sC`k!VL%(8R%p;`N75bYV=(mZstPC|MIhH-=;PlsgTo&$;jB$?mbJrXBiBv%8QEdG-KwWC*@@qTMzyW-$}ctG3awBg$fL
Y2dSE30D#9t{~_+`cKH2Y}hdx@*#IMps}HwbNxZDt<hF5O;v%VSWq#b%6GcpG$2(>jLigX)Q6NH)dHi7(3=dVu9J;2Ph%ufXI-S$
$w7MuEU8%trw5gDtx%$Ds@PqN7T=vK6Hc8K+4A0v5EGY|ut4)hBW?&z`<B&Fq=BnS!3^FwIQnPSr{~mNpiPT+tYXtVGt9Y{rZ7N;
2RZ1@rgM9*5{0$7Ae<8kcvM8SN=t$1>w*rU6DK;crma3UXEmJU_!d9g3AlE_9_VZDv@a>eP9ynkBeQD*4f!~9TrUen+wV^fsJ2GK
v|Y9Ie_(^|wL=fEMS1@(z~U;WNkw;eIXFE+0eFNuK~AIDXMtG2pfLwo+{?X!y#zh?x@vUOu00ixjF$BaCu_1rzqZT553zBZx&vYi
JT9P1znuUT=s)CC?a>&ms>42R;#J>(VGgC~W69g&N*uI3`|ZQo$Mg4R7uQ$e#pRo`@ca!b{+`3kjwc=tZR~p2!6|dU2wFC+;5(kX
Y@d^&S78#nX%G`Zb(&$qj}BA0<t}6%IE`@1+=`AhZP09|`PL&^G^hUVd=wwQ`}T4KUX|_G)KUews37px8)DWy=C6Yn2CqgDVSNm&
V#H@vJ$RmbkMyuMVIH1`MjD;?MPsKo#gDlsY;BJgnC;{#V-6GMw6<;|(w7)9&^;cbj;141ReV%0)>%kHx(8Hj;OGtMYgfNzNE&hU
^x5&gv-+;>**dqsrEZiPpupbMfX-;PauH_hDBPxRzG&k7d(dXjAlS~RS#<#>o`ck3s0y=VNtJ+z`a|Mb$7DX2L?KwJci;){WKVH?
BfgwC3qj**Mb$nhO&jVs{bo<Mh&gkk5l*;sdE2&&<XUB}`YNxkjoFV?bGVx8_^6CKOJMft${sew1Cw`D&l$@Xh(>;#qN9P^P$}Cx
wgr9sX53fA%JbtpDw<N(7O4O~kk6f?)ds?A9)}q9^K3TAG~fdowh^BD3HjaLYE>1@rJ!#5m`95A<D3BA#fKD+Y|ftq=zU&Qplb&d
lvMbq>z|MnZYp`4>yUtZ>07&M#1>b?I%jDyFlZNGA9v4e;kW@Be5m&^^EOL!g~ue~%@Q43=-saDY1NDn74=ty?=yrA=Ikwo`udE0
o{NL8jq;y)+<&WB>>`!uD<s@8Zr%J)r_6F&4QbPuM7#Er1K<s?alanu8YV8|>#v)%ZmQoivMJKoS|rw~G~EvUv<Gn;<%OF?U0Q2)
tGbN2z?=Us)>--6#zOn1WwPimXbVt%K0O-uoo>W>%9k7J4^1YPEd~@pRDP|0_uRRMhLP#+r1+h2I#tzU$D<`zR~_|U?$^TwjC_53
%a!M>*YSMrUL&>Xc0k6pr}5qhlc6BL?MPB{5zVorq{y+{ETIA?mF5rVJAOW*z!GLQ6y6Z5nOU1I%i1*{zrtDpeGxF;Axme?&0&11
T`6lU=@&Y4lnH&)2*TppseJBuCMIfk2)pXGe}=(;MDTKkQ%BDE=B^45hs1Uos;<mhqg346$FQpDbU^TcCyK(xA~>!~z6X)e3F4<u
es<L|)y8!FgJ!B*bh1?|j#_RjfG)P3f{AUW2^|1q`vqF{n^nC4_wx!zpZN13p&7PGa!qK5>LYyw`SwX;>UB=fb`SH?bssK9*L>K)
zT{&LYd)upyNkzS@!Wr}J*cm$*syR0M$rvTldJQe5t8p37<{APkWLDQOIRac&Czq!qjnjF!ntOH&qm;cx>u;6(Fk5N9+I$hKPMff
m3Oy{ktJxrzXmt+c!GCO^8d$JqCM&Ac9q066|QaN;tg3(t`$y=D~+oL3f)<`&#2#V%c65bii5VE2|Vn%$+6cd)U~DUn>eNtFe}Zz
5S_w{8GQMiq$v_ItPTT7F9iBfC^#k8!FgLJ=8{3r<m`ESOY2w`fh3BX%-*Wrhok1GR%Xum;(Z%0no#|iPU)lRgnQzPf07wxw#4_>
+gu=v^fuAr8om+FJ4b17OH?Xlffp_hf~S}r|AMEi?aihm?CE!nDz5NsJbEojwv@m3->%44D)v{ucOo_<u6Q()*JuY;utwgTp!W_W
95;TTi$lp25DdsH%5ji2$+R=g&VIKq?x($NZ9CouK(}0R4vcR4pqs7kFoTDERpnA*&kmbw2wh>g<!%*SoD`BtrehP^&&=Zqxj%I$
%k7ihm$G>JP8KvSof}!aEf=!j4L$!4Z)Dkf8_V9ySo#NcH)l5tEy4^Kx>>Y=^Yq#Af!DaS9T_d}kHrr<hs>kkg;9S!KHgi(W16G!
iWcisRu6bb?=jIcK)}n%^DJ)NbGPJ5KofGa*U0EJHrv?lY_{E*=JIj-cG2xu8Sc1SMNeoHP4luc*QyLjFO0D|LRDa4ms`XwL)p9<
=g|J`J6lY)XI42>ITV&6$4XaI&>#&H!*FNM!=ElczCIg!$87;cx5tp+nt<Q||IayHs%<OW89H}ef@BsyfB1An_xwk(KJtTirD4T5
%nx;cuVljcevvbnjdwInvLo$a-WX4_nK|sU<23Gb7Ja^|XJQg#|K|NO>;D0QXDLA
"""
EXPECTED_SHA256 = "58b422905c243f0b2b2faa83da8ebe811e48d33b0dc9c4d47ad26bafc4c138d1"

def run():
    wrapper = Path(sys.argv[1]).resolve()
    work = Path(os.environ.get(
        'OM_WORK', '/group-volume/' + os.environ.get('OM_USER', 'minsoo3.kim')
        + '/offpolicy-misranking'))
    candidates = []
    if wrapper.parent.name == 'scripts':
        candidates.append(wrapper.parent.parent)
    candidates.extend((Path.cwd(), work))
    repo = next((path.resolve() for path in candidates
                 if (path / 'src/selector_pair_gpu.py').is_file()), None)
    if repo is None:
        print('[handoff-abort] existing Pair checkout not found; run this file '
              'from the existing repository; nothing was stopped or changed',
              file=sys.stderr, flush=True)
        return 2
    raw = zlib.decompress(base64.b85decode(''.join(PAYLOAD.split())))
    if hashlib.sha256(raw).hexdigest() != EXPECTED_SHA256:
        raise RuntimeError('embedded handoff payload checksum mismatch')
    sources = json.loads(raw)
    for name in ('selector_pair_diagnostic', 'selector_pair_handoff'):
        module = types.ModuleType(name)
        module.__file__ = str(repo / 'scripts' / (name + '.py'))
        sys.modules[name] = module
        exec(compile(sources[name], module.__file__, 'exec'), module.__dict__)
    sys.argv = [str(repo / 'scripts/selector_pair_handoff.py'), *sys.argv[2:]]
    return sys.modules['selector_pair_handoff'].main()

raise SystemExit(run())
PAIR_HANDOFF_PYTHON
